// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_alert_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_alert_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "associated_detection.pb.h"
#include "associated_file.pb.h"
#include "location.pb.h"
#include "range_bearing.pb.h"
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_alert_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_alert_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_alert_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class Alert;
struct AlertDefaultTypeInternal;
extern AlertDefaultTypeInternal _Alert_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::Alert* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::Alert>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

enum Alert_AlertType : int {
  Alert_AlertType_ALERT_TYPE_UNSPECIFIED = 0,
  Alert_AlertType_ALERT_TYPE_INFORMATION = 1,
  Alert_AlertType_ALERT_TYPE_WARNING = 2,
  Alert_AlertType_ALERT_TYPE_CRITICAL = 3,
  Alert_AlertType_ALERT_TYPE_ERROR = 4,
  Alert_AlertType_ALERT_TYPE_FATAL = 5,
  Alert_AlertType_ALERT_TYPE_MODE_CHANGE = 6,
  Alert_AlertType_Alert_AlertType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Alert_AlertType_Alert_AlertType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Alert_AlertType_IsValid(int value);
constexpr Alert_AlertType Alert_AlertType_AlertType_MIN = Alert_AlertType_ALERT_TYPE_UNSPECIFIED;
constexpr Alert_AlertType Alert_AlertType_AlertType_MAX = Alert_AlertType_ALERT_TYPE_MODE_CHANGE;
constexpr int Alert_AlertType_AlertType_ARRAYSIZE = Alert_AlertType_AlertType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_AlertType_descriptor();
template<typename T>
inline const std::string& Alert_AlertType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Alert_AlertType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Alert_AlertType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Alert_AlertType_descriptor(), enum_t_value);
}
inline bool Alert_AlertType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Alert_AlertType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Alert_AlertType>(
    Alert_AlertType_descriptor(), name, value);
}
enum Alert_AlertStatus : int {
  Alert_AlertStatus_ALERT_STATUS_UNSPECIFIED = 0,
  Alert_AlertStatus_ALERT_STATUS_ACTIVE = 1,
  Alert_AlertStatus_ALERT_STATUS_ACKNOWLEDGE = 2,
  Alert_AlertStatus_ALERT_STATUS_REJECT = 3,
  Alert_AlertStatus_ALERT_STATUS_IGNORE = 4,
  Alert_AlertStatus_ALERT_STATUS_CLEAR = 5,
  Alert_AlertStatus_Alert_AlertStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Alert_AlertStatus_Alert_AlertStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Alert_AlertStatus_IsValid(int value);
constexpr Alert_AlertStatus Alert_AlertStatus_AlertStatus_MIN = Alert_AlertStatus_ALERT_STATUS_UNSPECIFIED;
constexpr Alert_AlertStatus Alert_AlertStatus_AlertStatus_MAX = Alert_AlertStatus_ALERT_STATUS_CLEAR;
constexpr int Alert_AlertStatus_AlertStatus_ARRAYSIZE = Alert_AlertStatus_AlertStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_AlertStatus_descriptor();
template<typename T>
inline const std::string& Alert_AlertStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Alert_AlertStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Alert_AlertStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Alert_AlertStatus_descriptor(), enum_t_value);
}
inline bool Alert_AlertStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Alert_AlertStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Alert_AlertStatus>(
    Alert_AlertStatus_descriptor(), name, value);
}
enum Alert_DiscretePriority : int {
  Alert_DiscretePriority_DISCRETE_PRIORITY_UNSPECIFIED = 0,
  Alert_DiscretePriority_DISCRETE_PRIORITY_LOW = 1,
  Alert_DiscretePriority_DISCRETE_PRIORITY_MEDIUM = 2,
  Alert_DiscretePriority_DISCRETE_PRIORITY_HIGH = 3,
  Alert_DiscretePriority_Alert_DiscretePriority_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Alert_DiscretePriority_Alert_DiscretePriority_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Alert_DiscretePriority_IsValid(int value);
constexpr Alert_DiscretePriority Alert_DiscretePriority_DiscretePriority_MIN = Alert_DiscretePriority_DISCRETE_PRIORITY_UNSPECIFIED;
constexpr Alert_DiscretePriority Alert_DiscretePriority_DiscretePriority_MAX = Alert_DiscretePriority_DISCRETE_PRIORITY_HIGH;
constexpr int Alert_DiscretePriority_DiscretePriority_ARRAYSIZE = Alert_DiscretePriority_DiscretePriority_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_DiscretePriority_descriptor();
template<typename T>
inline const std::string& Alert_DiscretePriority_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Alert_DiscretePriority>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Alert_DiscretePriority_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Alert_DiscretePriority_descriptor(), enum_t_value);
}
inline bool Alert_DiscretePriority_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Alert_DiscretePriority* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Alert_DiscretePriority>(
    Alert_DiscretePriority_descriptor(), name, value);
}
// ===================================================================

class Alert final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.Alert) */ {
 public:
  inline Alert() : Alert(nullptr) {}
  ~Alert() override;
  explicit PROTOBUF_CONSTEXPR Alert(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Alert(const Alert& from);
  Alert(Alert&& from) noexcept
    : Alert() {
    *this = ::std::move(from);
  }

  inline Alert& operator=(const Alert& from) {
    CopyFrom(from);
    return *this;
  }
  inline Alert& operator=(Alert&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Alert& default_instance() {
    return *internal_default_instance();
  }
  enum LocationOneofCase {
    kRangeBearing = 5,
    kLocation = 6,
    LOCATION_ONEOF_NOT_SET = 0,
  };

  static inline const Alert* internal_default_instance() {
    return reinterpret_cast<const Alert*>(
               &_Alert_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Alert& a, Alert& b) {
    a.Swap(&b);
  }
  inline void Swap(Alert* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Alert* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Alert* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Alert>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Alert& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Alert& from) {
    Alert::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Alert* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.Alert";
  }
  protected:
  explicit Alert(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Alert_AlertType AlertType;
  static constexpr AlertType ALERT_TYPE_UNSPECIFIED =
    Alert_AlertType_ALERT_TYPE_UNSPECIFIED;
  static constexpr AlertType ALERT_TYPE_INFORMATION =
    Alert_AlertType_ALERT_TYPE_INFORMATION;
  static constexpr AlertType ALERT_TYPE_WARNING =
    Alert_AlertType_ALERT_TYPE_WARNING;
  static constexpr AlertType ALERT_TYPE_CRITICAL =
    Alert_AlertType_ALERT_TYPE_CRITICAL;
  static constexpr AlertType ALERT_TYPE_ERROR =
    Alert_AlertType_ALERT_TYPE_ERROR;
  static constexpr AlertType ALERT_TYPE_FATAL =
    Alert_AlertType_ALERT_TYPE_FATAL;
  static constexpr AlertType ALERT_TYPE_MODE_CHANGE =
    Alert_AlertType_ALERT_TYPE_MODE_CHANGE;
  static inline bool AlertType_IsValid(int value) {
    return Alert_AlertType_IsValid(value);
  }
  static constexpr AlertType AlertType_MIN =
    Alert_AlertType_AlertType_MIN;
  static constexpr AlertType AlertType_MAX =
    Alert_AlertType_AlertType_MAX;
  static constexpr int AlertType_ARRAYSIZE =
    Alert_AlertType_AlertType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  AlertType_descriptor() {
    return Alert_AlertType_descriptor();
  }
  template<typename T>
  static inline const std::string& AlertType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, AlertType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function AlertType_Name.");
    return Alert_AlertType_Name(enum_t_value);
  }
  static inline bool AlertType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      AlertType* value) {
    return Alert_AlertType_Parse(name, value);
  }

  typedef Alert_AlertStatus AlertStatus;
  static constexpr AlertStatus ALERT_STATUS_UNSPECIFIED =
    Alert_AlertStatus_ALERT_STATUS_UNSPECIFIED;
  static constexpr AlertStatus ALERT_STATUS_ACTIVE =
    Alert_AlertStatus_ALERT_STATUS_ACTIVE;
  static constexpr AlertStatus ALERT_STATUS_ACKNOWLEDGE =
    Alert_AlertStatus_ALERT_STATUS_ACKNOWLEDGE;
  static constexpr AlertStatus ALERT_STATUS_REJECT =
    Alert_AlertStatus_ALERT_STATUS_REJECT;
  static constexpr AlertStatus ALERT_STATUS_IGNORE =
    Alert_AlertStatus_ALERT_STATUS_IGNORE;
  static constexpr AlertStatus ALERT_STATUS_CLEAR =
    Alert_AlertStatus_ALERT_STATUS_CLEAR;
  static inline bool AlertStatus_IsValid(int value) {
    return Alert_AlertStatus_IsValid(value);
  }
  static constexpr AlertStatus AlertStatus_MIN =
    Alert_AlertStatus_AlertStatus_MIN;
  static constexpr AlertStatus AlertStatus_MAX =
    Alert_AlertStatus_AlertStatus_MAX;
  static constexpr int AlertStatus_ARRAYSIZE =
    Alert_AlertStatus_AlertStatus_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  AlertStatus_descriptor() {
    return Alert_AlertStatus_descriptor();
  }
  template<typename T>
  static inline const std::string& AlertStatus_Name(T enum_t_value) {
    static_assert(::std::is_same<T, AlertStatus>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function AlertStatus_Name.");
    return Alert_AlertStatus_Name(enum_t_value);
  }
  static inline bool AlertStatus_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      AlertStatus* value) {
    return Alert_AlertStatus_Parse(name, value);
  }

  typedef Alert_DiscretePriority DiscretePriority;
  static constexpr DiscretePriority DISCRETE_PRIORITY_UNSPECIFIED =
    Alert_DiscretePriority_DISCRETE_PRIORITY_UNSPECIFIED;
  static constexpr DiscretePriority DISCRETE_PRIORITY_LOW =
    Alert_DiscretePriority_DISCRETE_PRIORITY_LOW;
  static constexpr DiscretePriority DISCRETE_PRIORITY_MEDIUM =
    Alert_DiscretePriority_DISCRETE_PRIORITY_MEDIUM;
  static constexpr DiscretePriority DISCRETE_PRIORITY_HIGH =
    Alert_DiscretePriority_DISCRETE_PRIORITY_HIGH;
  static inline bool DiscretePriority_IsValid(int value) {
    return Alert_DiscretePriority_IsValid(value);
  }
  static constexpr DiscretePriority DiscretePriority_MIN =
    Alert_DiscretePriority_DiscretePriority_MIN;
  static constexpr DiscretePriority DiscretePriority_MAX =
    Alert_DiscretePriority_DiscretePriority_MAX;
  static constexpr int DiscretePriority_ARRAYSIZE =
    Alert_DiscretePriority_DiscretePriority_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  DiscretePriority_descriptor() {
    return Alert_DiscretePriority_descriptor();
  }
  template<typename T>
  static inline const std::string& DiscretePriority_Name(T enum_t_value) {
    static_assert(::std::is_same<T, DiscretePriority>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function DiscretePriority_Name.");
    return Alert_DiscretePriority_Name(enum_t_value);
  }
  static inline bool DiscretePriority_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      DiscretePriority* value) {
    return Alert_DiscretePriority_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kAssociatedFileFieldNumber = 11,
    kAssociatedDetectionFieldNumber = 12,
    kAlertIdFieldNumber = 1,
    kDescriptionFieldNumber = 4,
    kRegionIdFieldNumber = 7,
    kAdditionalInformationFieldNumber = 13,
    kAlertTypeFieldNumber = 2,
    kStatusFieldNumber = 3,
    kPriorityFieldNumber = 8,
    kRankingFieldNumber = 9,
    kConfidenceFieldNumber = 10,
    kRangeBearingFieldNumber = 5,
    kLocationFieldNumber = 6,
  };
  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedFile associated_file = 11;
  int associated_file_size() const;
  private:
  int _internal_associated_file_size() const;
  public:
  void clear_associated_file();
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* mutable_associated_file(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >*
      mutable_associated_file();
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile& _internal_associated_file(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* _internal_add_associated_file();
  public:
  const ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile& associated_file(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* add_associated_file();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >&
      associated_file() const;

  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedDetection associated_detection = 12;
  int associated_detection_size() const;
  private:
  int _internal_associated_detection_size() const;
  public:
  void clear_associated_detection();
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* mutable_associated_detection(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >*
      mutable_associated_detection();
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection& _internal_associated_detection(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* _internal_add_associated_detection();
  public:
  const ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection& associated_detection(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* add_associated_detection();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >&
      associated_detection() const;

  // optional string alert_id = 1 [(.sapient_msg.field_options) = {
  bool has_alert_id() const;
  private:
  bool _internal_has_alert_id() const;
  public:
  void clear_alert_id();
  const std::string& alert_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_alert_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_alert_id();
  PROTOBUF_NODISCARD std::string* release_alert_id();
  void set_allocated_alert_id(std::string* alert_id);
  private:
  const std::string& _internal_alert_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_alert_id(const std::string& value);
  std::string* _internal_mutable_alert_id();
  public:

  // optional string description = 4;
  bool has_description() const;
  private:
  bool _internal_has_description() const;
  public:
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // optional string region_id = 7 [(.sapient_msg.field_options) = {
  bool has_region_id() const;
  private:
  bool _internal_has_region_id() const;
  public:
  void clear_region_id();
  const std::string& region_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_region_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_region_id();
  PROTOBUF_NODISCARD std::string* release_region_id();
  void set_allocated_region_id(std::string* region_id);
  private:
  const std::string& _internal_region_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_region_id(const std::string& value);
  std::string* _internal_mutable_region_id();
  public:

  // optional string additional_information = 13;
  bool has_additional_information() const;
  private:
  bool _internal_has_additional_information() const;
  public:
  void clear_additional_information();
  const std::string& additional_information() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_additional_information(ArgT0&& arg0, ArgT... args);
  std::string* mutable_additional_information();
  PROTOBUF_NODISCARD std::string* release_additional_information();
  void set_allocated_additional_information(std::string* additional_information);
  private:
  const std::string& _internal_additional_information() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_additional_information(const std::string& value);
  std::string* _internal_mutable_additional_information();
  public:

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertType alert_type = 2;
  bool has_alert_type() const;
  private:
  bool _internal_has_alert_type() const;
  public:
  void clear_alert_type();
  ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType alert_type() const;
  void set_alert_type(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType _internal_alert_type() const;
  void _internal_set_alert_type(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType value);
  public:

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus status = 3;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus status() const;
  void set_status(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus _internal_status() const;
  void _internal_set_status(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus value);
  public:

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority priority = 8;
  bool has_priority() const;
  private:
  bool _internal_has_priority() const;
  public:
  void clear_priority();
  ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority priority() const;
  void set_priority(::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority _internal_priority() const;
  void _internal_set_priority(::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority value);
  public:

  // optional float ranking = 9;
  bool has_ranking() const;
  private:
  bool _internal_has_ranking() const;
  public:
  void clear_ranking();
  float ranking() const;
  void set_ranking(float value);
  private:
  float _internal_ranking() const;
  void _internal_set_ranking(float value);
  public:

  // optional float confidence = 10;
  bool has_confidence() const;
  private:
  bool _internal_has_confidence() const;
  public:
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // .sapient_msg.bsi_flex_335_v2_0.RangeBearing range_bearing = 5;
  bool has_range_bearing() const;
  private:
  bool _internal_has_range_bearing() const;
  public:
  void clear_range_bearing();
  const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing& range_bearing() const;
  PROTOBUF_NODISCARD ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* release_range_bearing();
  ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* mutable_range_bearing();
  void set_allocated_range_bearing(::sapient_msg::bsi_flex_335_v2_0::RangeBearing* range_bearing);
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing& _internal_range_bearing() const;
  ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* _internal_mutable_range_bearing();
  public:
  void unsafe_arena_set_allocated_range_bearing(
      ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* range_bearing);
  ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* unsafe_arena_release_range_bearing();

  // .sapient_msg.bsi_flex_335_v2_0.Location location = 6;
  bool has_location() const;
  private:
  bool _internal_has_location() const;
  public:
  void clear_location();
  const ::sapient_msg::bsi_flex_335_v2_0::Location& location() const;
  PROTOBUF_NODISCARD ::sapient_msg::bsi_flex_335_v2_0::Location* release_location();
  ::sapient_msg::bsi_flex_335_v2_0::Location* mutable_location();
  void set_allocated_location(::sapient_msg::bsi_flex_335_v2_0::Location* location);
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::Location& _internal_location() const;
  ::sapient_msg::bsi_flex_335_v2_0::Location* _internal_mutable_location();
  public:
  void unsafe_arena_set_allocated_location(
      ::sapient_msg::bsi_flex_335_v2_0::Location* location);
  ::sapient_msg::bsi_flex_335_v2_0::Location* unsafe_arena_release_location();

  void clear_location_oneof();
  LocationOneofCase location_oneof_case() const;
  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.Alert)
 private:
  class _Internal;
  void set_has_range_bearing();
  void set_has_location();

  inline bool has_location_oneof() const;
  inline void clear_has_location_oneof();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile > associated_file_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection > associated_detection_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr alert_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr additional_information_;
    int alert_type_;
    int status_;
    int priority_;
    float ranking_;
    float confidence_;
    union LocationOneofUnion {
      constexpr LocationOneofUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* range_bearing_;
      ::sapient_msg::bsi_flex_335_v2_0::Location* location_;
    } location_oneof_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_alert_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Alert

// optional string alert_id = 1 [(.sapient_msg.field_options) = {
inline bool Alert::_internal_has_alert_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Alert::has_alert_id() const {
  return _internal_has_alert_id();
}
inline void Alert::clear_alert_id() {
  _impl_.alert_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Alert::alert_id() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.alert_id)
  return _internal_alert_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Alert::set_alert_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.alert_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.alert_id)
}
inline std::string* Alert::mutable_alert_id() {
  std::string* _s = _internal_mutable_alert_id();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.alert_id)
  return _s;
}
inline const std::string& Alert::_internal_alert_id() const {
  return _impl_.alert_id_.Get();
}
inline void Alert::_internal_set_alert_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.alert_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Alert::_internal_mutable_alert_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.alert_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Alert::release_alert_id() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.alert_id)
  if (!_internal_has_alert_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.alert_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.alert_id_.IsDefault()) {
    _impl_.alert_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Alert::set_allocated_alert_id(std::string* alert_id) {
  if (alert_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.alert_id_.SetAllocated(alert_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.alert_id_.IsDefault()) {
    _impl_.alert_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.alert_id)
}

// optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertType alert_type = 2;
inline bool Alert::_internal_has_alert_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Alert::has_alert_type() const {
  return _internal_has_alert_type();
}
inline void Alert::clear_alert_type() {
  _impl_.alert_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType Alert::_internal_alert_type() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType >(_impl_.alert_type_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType Alert::alert_type() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.alert_type)
  return _internal_alert_type();
}
inline void Alert::_internal_set_alert_type(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.alert_type_ = value;
}
inline void Alert::set_alert_type(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType value) {
  _internal_set_alert_type(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.alert_type)
}

// optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus status = 3;
inline bool Alert::_internal_has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Alert::has_status() const {
  return _internal_has_status();
}
inline void Alert::clear_status() {
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus Alert::_internal_status() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus >(_impl_.status_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus Alert::status() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.status)
  return _internal_status();
}
inline void Alert::_internal_set_status(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.status_ = value;
}
inline void Alert::set_status(::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.status)
}

// optional string description = 4;
inline bool Alert::_internal_has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Alert::has_description() const {
  return _internal_has_description();
}
inline void Alert::clear_description() {
  _impl_.description_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Alert::description() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Alert::set_description(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.description)
}
inline std::string* Alert::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.description)
  return _s;
}
inline const std::string& Alert::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Alert::_internal_set_description(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Alert::_internal_mutable_description() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* Alert::release_description() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.description)
  if (!_internal_has_description()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.description_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Alert::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.description)
}

// .sapient_msg.bsi_flex_335_v2_0.RangeBearing range_bearing = 5;
inline bool Alert::_internal_has_range_bearing() const {
  return location_oneof_case() == kRangeBearing;
}
inline bool Alert::has_range_bearing() const {
  return _internal_has_range_bearing();
}
inline void Alert::set_has_range_bearing() {
  _impl_._oneof_case_[0] = kRangeBearing;
}
inline ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* Alert::release_range_bearing() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
  if (_internal_has_range_bearing()) {
    clear_has_location_oneof();
    ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* temp = _impl_.location_oneof_.range_bearing_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.location_oneof_.range_bearing_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing& Alert::_internal_range_bearing() const {
  return _internal_has_range_bearing()
      ? *_impl_.location_oneof_.range_bearing_
      : reinterpret_cast< ::sapient_msg::bsi_flex_335_v2_0::RangeBearing&>(::sapient_msg::bsi_flex_335_v2_0::_RangeBearing_default_instance_);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing& Alert::range_bearing() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
  return _internal_range_bearing();
}
inline ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* Alert::unsafe_arena_release_range_bearing() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
  if (_internal_has_range_bearing()) {
    clear_has_location_oneof();
    ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* temp = _impl_.location_oneof_.range_bearing_;
    _impl_.location_oneof_.range_bearing_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Alert::unsafe_arena_set_allocated_range_bearing(::sapient_msg::bsi_flex_335_v2_0::RangeBearing* range_bearing) {
  clear_location_oneof();
  if (range_bearing) {
    set_has_range_bearing();
    _impl_.location_oneof_.range_bearing_ = range_bearing;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
}
inline ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* Alert::_internal_mutable_range_bearing() {
  if (!_internal_has_range_bearing()) {
    clear_location_oneof();
    set_has_range_bearing();
    _impl_.location_oneof_.range_bearing_ = CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::RangeBearing >(GetArenaForAllocation());
  }
  return _impl_.location_oneof_.range_bearing_;
}
inline ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* Alert::mutable_range_bearing() {
  ::sapient_msg::bsi_flex_335_v2_0::RangeBearing* _msg = _internal_mutable_range_bearing();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
  return _msg;
}

// .sapient_msg.bsi_flex_335_v2_0.Location location = 6;
inline bool Alert::_internal_has_location() const {
  return location_oneof_case() == kLocation;
}
inline bool Alert::has_location() const {
  return _internal_has_location();
}
inline void Alert::set_has_location() {
  _impl_._oneof_case_[0] = kLocation;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* Alert::release_location() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.location)
  if (_internal_has_location()) {
    clear_has_location_oneof();
    ::sapient_msg::bsi_flex_335_v2_0::Location* temp = _impl_.location_oneof_.location_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.location_oneof_.location_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Location& Alert::_internal_location() const {
  return _internal_has_location()
      ? *_impl_.location_oneof_.location_
      : reinterpret_cast< ::sapient_msg::bsi_flex_335_v2_0::Location&>(::sapient_msg::bsi_flex_335_v2_0::_Location_default_instance_);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Location& Alert::location() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.location)
  return _internal_location();
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* Alert::unsafe_arena_release_location() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sapient_msg.bsi_flex_335_v2_0.Alert.location)
  if (_internal_has_location()) {
    clear_has_location_oneof();
    ::sapient_msg::bsi_flex_335_v2_0::Location* temp = _impl_.location_oneof_.location_;
    _impl_.location_oneof_.location_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Alert::unsafe_arena_set_allocated_location(::sapient_msg::bsi_flex_335_v2_0::Location* location) {
  clear_location_oneof();
  if (location) {
    set_has_location();
    _impl_.location_oneof_.location_ = location;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.location)
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* Alert::_internal_mutable_location() {
  if (!_internal_has_location()) {
    clear_location_oneof();
    set_has_location();
    _impl_.location_oneof_.location_ = CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::Location >(GetArenaForAllocation());
  }
  return _impl_.location_oneof_.location_;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* Alert::mutable_location() {
  ::sapient_msg::bsi_flex_335_v2_0::Location* _msg = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.location)
  return _msg;
}

// optional string region_id = 7 [(.sapient_msg.field_options) = {
inline bool Alert::_internal_has_region_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Alert::has_region_id() const {
  return _internal_has_region_id();
}
inline void Alert::clear_region_id() {
  _impl_.region_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Alert::region_id() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.region_id)
  return _internal_region_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Alert::set_region_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.region_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.region_id)
}
inline std::string* Alert::mutable_region_id() {
  std::string* _s = _internal_mutable_region_id();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.region_id)
  return _s;
}
inline const std::string& Alert::_internal_region_id() const {
  return _impl_.region_id_.Get();
}
inline void Alert::_internal_set_region_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.region_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Alert::_internal_mutable_region_id() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.region_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Alert::release_region_id() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.region_id)
  if (!_internal_has_region_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.region_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.region_id_.IsDefault()) {
    _impl_.region_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Alert::set_allocated_region_id(std::string* region_id) {
  if (region_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.region_id_.SetAllocated(region_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.region_id_.IsDefault()) {
    _impl_.region_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.region_id)
}

// optional .sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority priority = 8;
inline bool Alert::_internal_has_priority() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Alert::has_priority() const {
  return _internal_has_priority();
}
inline void Alert::clear_priority() {
  _impl_.priority_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority Alert::_internal_priority() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority >(_impl_.priority_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority Alert::priority() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.priority)
  return _internal_priority();
}
inline void Alert::_internal_set_priority(::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.priority_ = value;
}
inline void Alert::set_priority(::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.priority)
}

// optional float ranking = 9;
inline bool Alert::_internal_has_ranking() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Alert::has_ranking() const {
  return _internal_has_ranking();
}
inline void Alert::clear_ranking() {
  _impl_.ranking_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline float Alert::_internal_ranking() const {
  return _impl_.ranking_;
}
inline float Alert::ranking() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.ranking)
  return _internal_ranking();
}
inline void Alert::_internal_set_ranking(float value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.ranking_ = value;
}
inline void Alert::set_ranking(float value) {
  _internal_set_ranking(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.ranking)
}

// optional float confidence = 10;
inline bool Alert::_internal_has_confidence() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Alert::has_confidence() const {
  return _internal_has_confidence();
}
inline void Alert::clear_confidence() {
  _impl_.confidence_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline float Alert::_internal_confidence() const {
  return _impl_.confidence_;
}
inline float Alert::confidence() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.confidence)
  return _internal_confidence();
}
inline void Alert::_internal_set_confidence(float value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.confidence_ = value;
}
inline void Alert::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.confidence)
}

// repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedFile associated_file = 11;
inline int Alert::_internal_associated_file_size() const {
  return _impl_.associated_file_.size();
}
inline int Alert::associated_file_size() const {
  return _internal_associated_file_size();
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* Alert::mutable_associated_file(int index) {
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.associated_file)
  return _impl_.associated_file_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >*
Alert::mutable_associated_file() {
  // @@protoc_insertion_point(field_mutable_list:sapient_msg.bsi_flex_335_v2_0.Alert.associated_file)
  return &_impl_.associated_file_;
}
inline const ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile& Alert::_internal_associated_file(int index) const {
  return _impl_.associated_file_.Get(index);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile& Alert::associated_file(int index) const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.associated_file)
  return _internal_associated_file(index);
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* Alert::_internal_add_associated_file() {
  return _impl_.associated_file_.Add();
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* Alert::add_associated_file() {
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile* _add = _internal_add_associated_file();
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.Alert.associated_file)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >&
Alert::associated_file() const {
  // @@protoc_insertion_point(field_list:sapient_msg.bsi_flex_335_v2_0.Alert.associated_file)
  return _impl_.associated_file_;
}

// repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedDetection associated_detection = 12;
inline int Alert::_internal_associated_detection_size() const {
  return _impl_.associated_detection_.size();
}
inline int Alert::associated_detection_size() const {
  return _internal_associated_detection_size();
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* Alert::mutable_associated_detection(int index) {
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection)
  return _impl_.associated_detection_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >*
Alert::mutable_associated_detection() {
  // @@protoc_insertion_point(field_mutable_list:sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection)
  return &_impl_.associated_detection_;
}
inline const ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection& Alert::_internal_associated_detection(int index) const {
  return _impl_.associated_detection_.Get(index);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection& Alert::associated_detection(int index) const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection)
  return _internal_associated_detection(index);
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* Alert::_internal_add_associated_detection() {
  return _impl_.associated_detection_.Add();
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* Alert::add_associated_detection() {
  ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* _add = _internal_add_associated_detection();
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >&
Alert::associated_detection() const {
  // @@protoc_insertion_point(field_list:sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection)
  return _impl_.associated_detection_;
}

// optional string additional_information = 13;
inline bool Alert::_internal_has_additional_information() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Alert::has_additional_information() const {
  return _internal_has_additional_information();
}
inline void Alert::clear_additional_information() {
  _impl_.additional_information_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Alert::additional_information() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Alert.additional_information)
  return _internal_additional_information();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Alert::set_additional_information(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.additional_information_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Alert.additional_information)
}
inline std::string* Alert::mutable_additional_information() {
  std::string* _s = _internal_mutable_additional_information();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Alert.additional_information)
  return _s;
}
inline const std::string& Alert::_internal_additional_information() const {
  return _impl_.additional_information_.Get();
}
inline void Alert::_internal_set_additional_information(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.additional_information_.Set(value, GetArenaForAllocation());
}
inline std::string* Alert::_internal_mutable_additional_information() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.additional_information_.Mutable(GetArenaForAllocation());
}
inline std::string* Alert::release_additional_information() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Alert.additional_information)
  if (!_internal_has_additional_information()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.additional_information_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.additional_information_.IsDefault()) {
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Alert::set_allocated_additional_information(std::string* additional_information) {
  if (additional_information != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.additional_information_.SetAllocated(additional_information, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.additional_information_.IsDefault()) {
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.additional_information)
}

inline bool Alert::has_location_oneof() const {
  return location_oneof_case() != LOCATION_ONEOF_NOT_SET;
}
inline void Alert::clear_has_location_oneof() {
  _impl_._oneof_case_[0] = LOCATION_ONEOF_NOT_SET;
}
inline Alert::LocationOneofCase Alert::location_oneof_case() const {
  return Alert::LocationOneofCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType>() {
  return ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType_descriptor();
}
template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus>() {
  return ::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus_descriptor();
}
template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority>() {
  return ::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_alert_2eproto
