// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

#include "alert.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR Alert::Alert(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.associated_file_)*/{}
  , /*decltype(_impl_.associated_detection_)*/{}
  , /*decltype(_impl_.alert_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.description_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.region_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.additional_information_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alert_type_)*/0
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.priority_)*/0
  , /*decltype(_impl_.ranking_)*/0
  , /*decltype(_impl_.confidence_)*/0
  , /*decltype(_impl_.location_oneof_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct AlertDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AlertDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AlertDefaultTypeInternal() {}
  union {
    Alert _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AlertDefaultTypeInternal _Alert_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_alert_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_alert_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_alert_2eproto = nullptr;

const uint32_t TableStruct_alert_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.alert_id_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.alert_type_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.description_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.region_id_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.priority_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.ranking_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.confidence_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.associated_file_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.associated_detection_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.additional_information_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::Alert, _impl_.location_oneof_),
  0,
  4,
  5,
  1,
  ~0u,
  ~0u,
  2,
  6,
  7,
  8,
  ~0u,
  ~0u,
  3,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 20, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::Alert)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_Alert_default_instance_._instance,
};

const char descriptor_table_protodef_alert_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013alert.proto\022\035sapient_msg.bsi_flex_335_"
  "v2_0\032\032associated_detection.proto\032\025associ"
  "ated_file.proto\032\016location.proto\032\023range_b"
  "earing.proto\032\023proto_options.proto\"\306\n\n\005Al"
  "ert\022\037\n\010alert_id\030\001 \001(\tB\010\212\265\030\004\010\001\020\001H\001\210\001\001\022G\n\n"
  "alert_type\030\002 \001(\0162..sapient_msg.bsi_flex_"
  "335_v2_0.Alert.AlertTypeH\002\210\001\001\022E\n\006status\030"
  "\003 \001(\01620.sapient_msg.bsi_flex_335_v2_0.Al"
  "ert.AlertStatusH\003\210\001\001\022\030\n\013description\030\004 \001("
  "\tH\004\210\001\001\022D\n\rrange_bearing\030\005 \001(\0132+.sapient_"
  "msg.bsi_flex_335_v2_0.RangeBearingH\000\022;\n\010"
  "location\030\006 \001(\0132\'.sapient_msg.bsi_flex_33"
  "5_v2_0.LocationH\000\022\036\n\tregion_id\030\007 \001(\tB\006\212\265"
  "\030\002\020\001H\005\210\001\001\022L\n\010priority\030\010 \001(\01625.sapient_ms"
  "g.bsi_flex_335_v2_0.Alert.DiscretePriori"
  "tyH\006\210\001\001\022\024\n\007ranking\030\t \001(\002H\007\210\001\001\022\027\n\nconfide"
  "nce\030\n \001(\002H\010\210\001\001\022F\n\017associated_file\030\013 \003(\0132"
  "-.sapient_msg.bsi_flex_335_v2_0.Associat"
  "edFile\022P\n\024associated_detection\030\014 \003(\01322.s"
  "apient_msg.bsi_flex_335_v2_0.AssociatedD"
  "etection\022#\n\026additional_information\030\r \001(\t"
  "H\t\210\001\001\"\274\001\n\tAlertType\022\032\n\026ALERT_TYPE_UNSPEC"
  "IFIED\020\000\022\032\n\026ALERT_TYPE_INFORMATION\020\001\022\026\n\022A"
  "LERT_TYPE_WARNING\020\002\022\027\n\023ALERT_TYPE_CRITIC"
  "AL\020\003\022\024\n\020ALERT_TYPE_ERROR\020\004\022\024\n\020ALERT_TYPE"
  "_FATAL\020\005\022\032\n\026ALERT_TYPE_MODE_CHANGE\020\006\"\254\001\n"
  "\013AlertStatus\022\034\n\030ALERT_STATUS_UNSPECIFIED"
  "\020\000\022\027\n\023ALERT_STATUS_ACTIVE\020\001\022\034\n\030ALERT_STA"
  "TUS_ACKNOWLEDGE\020\002\022\027\n\023ALERT_STATUS_REJECT"
  "\020\003\022\027\n\023ALERT_STATUS_IGNORE\020\004\022\026\n\022ALERT_STA"
  "TUS_CLEAR\020\005\"\212\001\n\020DiscretePriority\022!\n\035DISC"
  "RETE_PRIORITY_UNSPECIFIED\020\000\022\031\n\025DISCRETE_"
  "PRIORITY_LOW\020\001\022\034\n\030DISCRETE_PRIORITY_MEDI"
  "UM\020\002\022\032\n\026DISCRETE_PRIORITY_HIGH\020\003B\020\n\016loca"
  "tion_oneofB\013\n\t_alert_idB\r\n\013_alert_typeB\t"
  "\n\007_statusB\016\n\014_descriptionB\014\n\n_region_idB"
  "\013\n\t_priorityB\n\n\010_rankingB\r\n\013_confidenceB"
  "\031\n\027_additional_informationB3\n#uk.gov.dst"
  "l.sapientmsg.bsiflex335v2B\nAlertProtoP\001b"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_alert_2eproto_deps[5] = {
  &::descriptor_table_associated_5fdetection_2eproto,
  &::descriptor_table_associated_5ffile_2eproto,
  &::descriptor_table_location_2eproto,
  &::descriptor_table_proto_5foptions_2eproto,
  &::descriptor_table_range_5fbearing_2eproto,
};
static ::_pbi::once_flag descriptor_table_alert_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_alert_2eproto = {
    false, false, 1567, descriptor_table_protodef_alert_2eproto,
    "alert.proto",
    &descriptor_table_alert_2eproto_once, descriptor_table_alert_2eproto_deps, 5, 1,
    schemas, file_default_instances, TableStruct_alert_2eproto::offsets,
    file_level_metadata_alert_2eproto, file_level_enum_descriptors_alert_2eproto,
    file_level_service_descriptors_alert_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_alert_2eproto_getter() {
  return &descriptor_table_alert_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_alert_2eproto(&descriptor_table_alert_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_AlertType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_alert_2eproto);
  return file_level_enum_descriptors_alert_2eproto[0];
}
bool Alert_AlertType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Alert_AlertType Alert::ALERT_TYPE_UNSPECIFIED;
constexpr Alert_AlertType Alert::ALERT_TYPE_INFORMATION;
constexpr Alert_AlertType Alert::ALERT_TYPE_WARNING;
constexpr Alert_AlertType Alert::ALERT_TYPE_CRITICAL;
constexpr Alert_AlertType Alert::ALERT_TYPE_ERROR;
constexpr Alert_AlertType Alert::ALERT_TYPE_FATAL;
constexpr Alert_AlertType Alert::ALERT_TYPE_MODE_CHANGE;
constexpr Alert_AlertType Alert::AlertType_MIN;
constexpr Alert_AlertType Alert::AlertType_MAX;
constexpr int Alert::AlertType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_AlertStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_alert_2eproto);
  return file_level_enum_descriptors_alert_2eproto[1];
}
bool Alert_AlertStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Alert_AlertStatus Alert::ALERT_STATUS_UNSPECIFIED;
constexpr Alert_AlertStatus Alert::ALERT_STATUS_ACTIVE;
constexpr Alert_AlertStatus Alert::ALERT_STATUS_ACKNOWLEDGE;
constexpr Alert_AlertStatus Alert::ALERT_STATUS_REJECT;
constexpr Alert_AlertStatus Alert::ALERT_STATUS_IGNORE;
constexpr Alert_AlertStatus Alert::ALERT_STATUS_CLEAR;
constexpr Alert_AlertStatus Alert::AlertStatus_MIN;
constexpr Alert_AlertStatus Alert::AlertStatus_MAX;
constexpr int Alert::AlertStatus_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Alert_DiscretePriority_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_alert_2eproto);
  return file_level_enum_descriptors_alert_2eproto[2];
}
bool Alert_DiscretePriority_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Alert_DiscretePriority Alert::DISCRETE_PRIORITY_UNSPECIFIED;
constexpr Alert_DiscretePriority Alert::DISCRETE_PRIORITY_LOW;
constexpr Alert_DiscretePriority Alert::DISCRETE_PRIORITY_MEDIUM;
constexpr Alert_DiscretePriority Alert::DISCRETE_PRIORITY_HIGH;
constexpr Alert_DiscretePriority Alert::DiscretePriority_MIN;
constexpr Alert_DiscretePriority Alert::DiscretePriority_MAX;
constexpr int Alert::DiscretePriority_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Alert::_Internal {
 public:
  using HasBits = decltype(std::declval<Alert>()._impl_._has_bits_);
  static void set_has_alert_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_alert_type(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_status(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_description(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing& range_bearing(const Alert* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::Location& location(const Alert* msg);
  static void set_has_region_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_priority(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_ranking(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_confidence(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_additional_information(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::sapient_msg::bsi_flex_335_v2_0::RangeBearing&
Alert::_Internal::range_bearing(const Alert* msg) {
  return *msg->_impl_.location_oneof_.range_bearing_;
}
const ::sapient_msg::bsi_flex_335_v2_0::Location&
Alert::_Internal::location(const Alert* msg) {
  return *msg->_impl_.location_oneof_.location_;
}
void Alert::set_allocated_range_bearing(::sapient_msg::bsi_flex_335_v2_0::RangeBearing* range_bearing) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_location_oneof();
  if (range_bearing) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(range_bearing));
    if (message_arena != submessage_arena) {
      range_bearing = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, range_bearing, submessage_arena);
    }
    set_has_range_bearing();
    _impl_.location_oneof_.range_bearing_ = range_bearing;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing)
}
void Alert::clear_range_bearing() {
  if (_internal_has_range_bearing()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.location_oneof_.range_bearing_;
    }
    clear_has_location_oneof();
  }
}
void Alert::set_allocated_location(::sapient_msg::bsi_flex_335_v2_0::Location* location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_location_oneof();
  if (location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(location));
    if (message_arena != submessage_arena) {
      location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, location, submessage_arena);
    }
    set_has_location();
    _impl_.location_oneof_.location_ = location;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Alert.location)
}
void Alert::clear_location() {
  if (_internal_has_location()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.location_oneof_.location_;
    }
    clear_has_location_oneof();
  }
}
void Alert::clear_associated_file() {
  _impl_.associated_file_.Clear();
}
void Alert::clear_associated_detection() {
  _impl_.associated_detection_.Clear();
}
Alert::Alert(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.Alert)
}
Alert::Alert(const Alert& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Alert* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.associated_file_){from._impl_.associated_file_}
    , decltype(_impl_.associated_detection_){from._impl_.associated_detection_}
    , decltype(_impl_.alert_id_){}
    , decltype(_impl_.description_){}
    , decltype(_impl_.region_id_){}
    , decltype(_impl_.additional_information_){}
    , decltype(_impl_.alert_type_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.priority_){}
    , decltype(_impl_.ranking_){}
    , decltype(_impl_.confidence_){}
    , decltype(_impl_.location_oneof_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.alert_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alert_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_alert_id()) {
    _this->_impl_.alert_id_.Set(from._internal_alert_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_description()) {
    _this->_impl_.description_.Set(from._internal_description(), 
      _this->GetArenaForAllocation());
  }
  _impl_.region_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_region_id()) {
    _this->_impl_.region_id_.Set(from._internal_region_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.additional_information_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_additional_information()) {
    _this->_impl_.additional_information_.Set(from._internal_additional_information(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.alert_type_, &from._impl_.alert_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.confidence_) -
    reinterpret_cast<char*>(&_impl_.alert_type_)) + sizeof(_impl_.confidence_));
  clear_has_location_oneof();
  switch (from.location_oneof_case()) {
    case kRangeBearing: {
      _this->_internal_mutable_range_bearing()->::sapient_msg::bsi_flex_335_v2_0::RangeBearing::MergeFrom(
          from._internal_range_bearing());
      break;
    }
    case kLocation: {
      _this->_internal_mutable_location()->::sapient_msg::bsi_flex_335_v2_0::Location::MergeFrom(
          from._internal_location());
      break;
    }
    case LOCATION_ONEOF_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.Alert)
}

inline void Alert::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.associated_file_){arena}
    , decltype(_impl_.associated_detection_){arena}
    , decltype(_impl_.alert_id_){}
    , decltype(_impl_.description_){}
    , decltype(_impl_.region_id_){}
    , decltype(_impl_.additional_information_){}
    , decltype(_impl_.alert_type_){0}
    , decltype(_impl_.status_){0}
    , decltype(_impl_.priority_){0}
    , decltype(_impl_.ranking_){0}
    , decltype(_impl_.confidence_){0}
    , decltype(_impl_.location_oneof_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.alert_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alert_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.region_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.additional_information_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_location_oneof();
}

Alert::~Alert() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.Alert)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Alert::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.associated_file_.~RepeatedPtrField();
  _impl_.associated_detection_.~RepeatedPtrField();
  _impl_.alert_id_.Destroy();
  _impl_.description_.Destroy();
  _impl_.region_id_.Destroy();
  _impl_.additional_information_.Destroy();
  if (has_location_oneof()) {
    clear_location_oneof();
  }
}

void Alert::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Alert::clear_location_oneof() {
// @@protoc_insertion_point(one_of_clear_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  switch (location_oneof_case()) {
    case kRangeBearing: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.location_oneof_.range_bearing_;
      }
      break;
    }
    case kLocation: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.location_oneof_.location_;
      }
      break;
    }
    case LOCATION_ONEOF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = LOCATION_ONEOF_NOT_SET;
}


void Alert::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.associated_file_.Clear();
  _impl_.associated_detection_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.alert_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.description_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.region_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.additional_information_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000f0u) {
    ::memset(&_impl_.alert_type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.ranking_) -
        reinterpret_cast<char*>(&_impl_.alert_type_)) + sizeof(_impl_.ranking_));
  }
  _impl_.confidence_ = 0;
  clear_location_oneof();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Alert::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string alert_id = 1 [(.sapient_msg.field_options) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_alert_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.Alert.alert_id"));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertType alert_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_alert_type(static_cast<::sapient_msg::bsi_flex_335_v2_0::Alert_AlertType>(val));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::sapient_msg::bsi_flex_335_v2_0::Alert_AlertStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // optional string description = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_description();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.Alert.description"));
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.RangeBearing range_bearing = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_range_bearing(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Location location = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_location(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string region_id = 7 [(.sapient_msg.field_options) = {
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_region_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.Alert.region_id"));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority priority = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_priority(static_cast<::sapient_msg::bsi_flex_335_v2_0::Alert_DiscretePriority>(val));
        } else
          goto handle_unusual;
        continue;
      // optional float ranking = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 77)) {
          _Internal::set_has_ranking(&has_bits);
          _impl_.ranking_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float confidence = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 85)) {
          _Internal::set_has_confidence(&has_bits);
          _impl_.confidence_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedFile associated_file = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_associated_file(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<90>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedDetection associated_detection = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_associated_detection(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<98>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional string additional_information = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_additional_information();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.Alert.additional_information"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Alert::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional string alert_id = 1 [(.sapient_msg.field_options) = {
  if (_internal_has_alert_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alert_id().data(), static_cast<int>(this->_internal_alert_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.Alert.alert_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_alert_id(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertType alert_type = 2;
  if (_internal_has_alert_type()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_alert_type(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus status = 3;
  if (_internal_has_status()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_status(), target);
  }

  // optional string description = 4;
  if (_internal_has_description()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.Alert.description");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_description(), target);
  }

  // .sapient_msg.bsi_flex_335_v2_0.RangeBearing range_bearing = 5;
  if (_internal_has_range_bearing()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::range_bearing(this),
        _Internal::range_bearing(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Location location = 6;
  if (_internal_has_location()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::location(this),
        _Internal::location(this).GetCachedSize(), target, stream);
  }

  // optional string region_id = 7 [(.sapient_msg.field_options) = {
  if (_internal_has_region_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_region_id().data(), static_cast<int>(this->_internal_region_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.Alert.region_id");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_region_id(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority priority = 8;
  if (_internal_has_priority()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      8, this->_internal_priority(), target);
  }

  // optional float ranking = 9;
  if (_internal_has_ranking()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(9, this->_internal_ranking(), target);
  }

  // optional float confidence = 10;
  if (_internal_has_confidence()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(10, this->_internal_confidence(), target);
  }

  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedFile associated_file = 11;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_associated_file_size()); i < n; i++) {
    const auto& repfield = this->_internal_associated_file(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(11, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedDetection associated_detection = 12;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_associated_detection_size()); i < n; i++) {
    const auto& repfield = this->_internal_associated_detection(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(12, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional string additional_information = 13;
  if (_internal_has_additional_information()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_additional_information().data(), static_cast<int>(this->_internal_additional_information().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.Alert.additional_information");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_additional_information(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.Alert)
  return target;
}

size_t Alert::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedFile associated_file = 11;
  total_size += 1UL * this->_internal_associated_file_size();
  for (const auto& msg : this->_impl_.associated_file_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .sapient_msg.bsi_flex_335_v2_0.AssociatedDetection associated_detection = 12;
  total_size += 1UL * this->_internal_associated_detection_size();
  for (const auto& msg : this->_impl_.associated_detection_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string alert_id = 1 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_alert_id());
    }

    // optional string description = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_description());
    }

    // optional string region_id = 7 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_region_id());
    }

    // optional string additional_information = 13;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_additional_information());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertType alert_type = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_alert_type());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus status = 3;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority priority = 8;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_priority());
    }

    // optional float ranking = 9;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 4;
    }

  }
  // optional float confidence = 10;
  if (cached_has_bits & 0x00000100u) {
    total_size += 1 + 4;
  }

  switch (location_oneof_case()) {
    // .sapient_msg.bsi_flex_335_v2_0.RangeBearing range_bearing = 5;
    case kRangeBearing: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.location_oneof_.range_bearing_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.Location location = 6;
    case kLocation: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.location_oneof_.location_);
      break;
    }
    case LOCATION_ONEOF_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Alert::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Alert::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Alert::GetClassData() const { return &_class_data_; }


void Alert::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Alert*>(&to_msg);
  auto& from = static_cast<const Alert&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.associated_file_.MergeFrom(from._impl_.associated_file_);
  _this->_impl_.associated_detection_.MergeFrom(from._impl_.associated_detection_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_alert_id(from._internal_alert_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_description(from._internal_description());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_region_id(from._internal_region_id());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_additional_information(from._internal_additional_information());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.alert_type_ = from._impl_.alert_type_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.status_ = from._impl_.status_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.priority_ = from._impl_.priority_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.ranking_ = from._impl_.ranking_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_confidence(from._internal_confidence());
  }
  switch (from.location_oneof_case()) {
    case kRangeBearing: {
      _this->_internal_mutable_range_bearing()->::sapient_msg::bsi_flex_335_v2_0::RangeBearing::MergeFrom(
          from._internal_range_bearing());
      break;
    }
    case kLocation: {
      _this->_internal_mutable_location()->::sapient_msg::bsi_flex_335_v2_0::Location::MergeFrom(
          from._internal_location());
      break;
    }
    case LOCATION_ONEOF_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Alert::CopyFrom(const Alert& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.Alert)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Alert::IsInitialized() const {
  return true;
}

void Alert::InternalSwap(Alert* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.associated_file_.InternalSwap(&other->_impl_.associated_file_);
  _impl_.associated_detection_.InternalSwap(&other->_impl_.associated_detection_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alert_id_, lhs_arena,
      &other->_impl_.alert_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.description_, lhs_arena,
      &other->_impl_.description_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.region_id_, lhs_arena,
      &other->_impl_.region_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.additional_information_, lhs_arena,
      &other->_impl_.additional_information_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Alert, _impl_.confidence_)
      + sizeof(Alert::_impl_.confidence_)
      - PROTOBUF_FIELD_OFFSET(Alert, _impl_.alert_type_)>(
          reinterpret_cast<char*>(&_impl_.alert_type_),
          reinterpret_cast<char*>(&other->_impl_.alert_type_));
  swap(_impl_.location_oneof_, other->_impl_.location_oneof_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Alert::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_alert_2eproto_getter, &descriptor_table_alert_2eproto_once,
      file_level_metadata_alert_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::Alert*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::Alert >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::Alert >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
