// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: associated_file.proto

#include "associated_file.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR AssociatedFile::AssociatedFile(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct AssociatedFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AssociatedFileDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AssociatedFileDefaultTypeInternal() {}
  union {
    AssociatedFile _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AssociatedFileDefaultTypeInternal _AssociatedFile_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_associated_5ffile_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_associated_5ffile_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_associated_5ffile_2eproto = nullptr;

const uint32_t TableStruct_associated_5ffile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedFile, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedFile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedFile, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedFile, _impl_.url_),
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::AssociatedFile)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_AssociatedFile_default_instance_._instance,
};

const char descriptor_table_protodef_associated_5ffile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025associated_file.proto\022\035sapient_msg.bsi"
  "_flex_335_v2_0\032\023proto_options.proto\"V\n\016A"
  "ssociatedFile\022\031\n\004type\030\001 \001(\tB\006\212\265\030\002\010\001H\000\210\001\001"
  "\022\030\n\003url\030\002 \001(\tB\006\212\265\030\002\010\001H\001\210\001\001B\007\n\005_typeB\006\n\004_"
  "urlB<\n#uk.gov.dstl.sapientmsg.bsiflex335"
  "v2B\023AssociatedFileProtoP\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_associated_5ffile_2eproto_deps[1] = {
  &::descriptor_table_proto_5foptions_2eproto,
};
static ::_pbi::once_flag descriptor_table_associated_5ffile_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_associated_5ffile_2eproto = {
    false, false, 233, descriptor_table_protodef_associated_5ffile_2eproto,
    "associated_file.proto",
    &descriptor_table_associated_5ffile_2eproto_once, descriptor_table_associated_5ffile_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_associated_5ffile_2eproto::offsets,
    file_level_metadata_associated_5ffile_2eproto, file_level_enum_descriptors_associated_5ffile_2eproto,
    file_level_service_descriptors_associated_5ffile_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_associated_5ffile_2eproto_getter() {
  return &descriptor_table_associated_5ffile_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_associated_5ffile_2eproto(&descriptor_table_associated_5ffile_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class AssociatedFile::_Internal {
 public:
  using HasBits = decltype(std::declval<AssociatedFile>()._impl_._has_bits_);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_url(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

AssociatedFile::AssociatedFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
}
AssociatedFile::AssociatedFile(const AssociatedFile& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AssociatedFile* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
    , decltype(_impl_.url_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_type()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_url()) {
    _this->_impl_.url_.Set(from._internal_url(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
}

inline void AssociatedFile::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
    , decltype(_impl_.url_){}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AssociatedFile::~AssociatedFile() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AssociatedFile::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  _impl_.url_.Destroy();
}

void AssociatedFile::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AssociatedFile::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.type_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.url_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AssociatedFile::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string type = 1 [(.sapient_msg.field_options) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.AssociatedFile.type"));
        } else
          goto handle_unusual;
        continue;
      // optional string url = 2 [(.sapient_msg.field_options) = {
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.AssociatedFile.url"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AssociatedFile::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional string type = 1 [(.sapient_msg.field_options) = {
  if (_internal_has_type()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.AssociatedFile.type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type(), target);
  }

  // optional string url = 2 [(.sapient_msg.field_options) = {
  if (_internal_has_url()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_url().data(), static_cast<int>(this->_internal_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.AssociatedFile.url");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_url(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  return target;
}

size_t AssociatedFile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string type = 1 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_type());
    }

    // optional string url = 2 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_url());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AssociatedFile::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AssociatedFile::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AssociatedFile::GetClassData() const { return &_class_data_; }


void AssociatedFile::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AssociatedFile*>(&to_msg);
  auto& from = static_cast<const AssociatedFile&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_type(from._internal_type());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_url(from._internal_url());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AssociatedFile::CopyFrom(const AssociatedFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.AssociatedFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AssociatedFile::IsInitialized() const {
  return true;
}

void AssociatedFile::InternalSwap(AssociatedFile* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.url_, lhs_arena,
      &other->_impl_.url_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AssociatedFile::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_associated_5ffile_2eproto_getter, &descriptor_table_associated_5ffile_2eproto_once,
      file_level_metadata_associated_5ffile_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::AssociatedFile >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
