// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: associated_detection.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_associated_5fdetection_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_associated_5fdetection_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_associated_5fdetection_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_associated_5fdetection_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_associated_5fdetection_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class AssociatedDetection;
struct AssociatedDetectionDefaultTypeInternal;
extern AssociatedDetectionDefaultTypeInternal _AssociatedDetection_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

enum AssociationRelation : int {
  ASSOCIATION_RELATION_UNSPECIFIED = 0,
  ASSOCIATION_RELATION_NO_RELATION = 1,
  ASSOCIATION_RELATION_PARENT = 2,
  ASSOCIATION_RELATION_CHILD = 3,
  ASSOCIATION_RELATION_SIBLING = 4,
  AssociationRelation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AssociationRelation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AssociationRelation_IsValid(int value);
constexpr AssociationRelation AssociationRelation_MIN = ASSOCIATION_RELATION_UNSPECIFIED;
constexpr AssociationRelation AssociationRelation_MAX = ASSOCIATION_RELATION_SIBLING;
constexpr int AssociationRelation_ARRAYSIZE = AssociationRelation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AssociationRelation_descriptor();
template<typename T>
inline const std::string& AssociationRelation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AssociationRelation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AssociationRelation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AssociationRelation_descriptor(), enum_t_value);
}
inline bool AssociationRelation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AssociationRelation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AssociationRelation>(
    AssociationRelation_descriptor(), name, value);
}
// ===================================================================

class AssociatedDetection final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection) */ {
 public:
  inline AssociatedDetection() : AssociatedDetection(nullptr) {}
  ~AssociatedDetection() override;
  explicit PROTOBUF_CONSTEXPR AssociatedDetection(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AssociatedDetection(const AssociatedDetection& from);
  AssociatedDetection(AssociatedDetection&& from) noexcept
    : AssociatedDetection() {
    *this = ::std::move(from);
  }

  inline AssociatedDetection& operator=(const AssociatedDetection& from) {
    CopyFrom(from);
    return *this;
  }
  inline AssociatedDetection& operator=(AssociatedDetection&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AssociatedDetection& default_instance() {
    return *internal_default_instance();
  }
  static inline const AssociatedDetection* internal_default_instance() {
    return reinterpret_cast<const AssociatedDetection*>(
               &_AssociatedDetection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AssociatedDetection& a, AssociatedDetection& b) {
    a.Swap(&b);
  }
  inline void Swap(AssociatedDetection* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AssociatedDetection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AssociatedDetection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AssociatedDetection>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AssociatedDetection& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AssociatedDetection& from) {
    AssociatedDetection::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AssociatedDetection* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.AssociatedDetection";
  }
  protected:
  explicit AssociatedDetection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 2,
    kObjectIdFieldNumber = 3,
    kTimestampFieldNumber = 1,
    kAssociationTypeFieldNumber = 4,
  };
  // optional string node_id = 2 [(.sapient_msg.field_options) = {
  bool has_node_id() const;
  private:
  bool _internal_has_node_id() const;
  public:
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // optional string object_id = 3 [(.sapient_msg.field_options) = {
  bool has_object_id() const;
  private:
  bool _internal_has_object_id() const;
  public:
  void clear_object_id();
  const std::string& object_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_object_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_object_id();
  PROTOBUF_NODISCARD std::string* release_object_id();
  void set_allocated_object_id(std::string* object_id);
  private:
  const std::string& _internal_object_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_object_id(const std::string& value);
  std::string* _internal_mutable_object_id();
  public:

  // optional .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // optional .sapient_msg.bsi_flex_335_v2_0.AssociationRelation association_type = 4;
  bool has_association_type() const;
  private:
  bool _internal_has_association_type() const;
  public:
  void clear_association_type();
  ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation association_type() const;
  void set_association_type(::sapient_msg::bsi_flex_335_v2_0::AssociationRelation value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation _internal_association_type() const;
  void _internal_set_association_type(::sapient_msg::bsi_flex_335_v2_0::AssociationRelation value);
  public:

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_id_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
    int association_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_associated_5fdetection_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AssociatedDetection

// optional .google.protobuf.Timestamp timestamp = 1;
inline bool AssociatedDetection::_internal_has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline bool AssociatedDetection::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& AssociatedDetection::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& AssociatedDetection::timestamp() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp)
  return _internal_timestamp();
}
inline void AssociatedDetection::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = timestamp;
  if (timestamp) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AssociatedDetection::release_timestamp() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AssociatedDetection::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AssociatedDetection::_internal_mutable_timestamp() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.timestamp_ = p;
  }
  return _impl_.timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AssociatedDetection::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp)
  return _msg;
}
inline void AssociatedDetection::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp)
}

// optional string node_id = 2 [(.sapient_msg.field_options) = {
inline bool AssociatedDetection::_internal_has_node_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AssociatedDetection::has_node_id() const {
  return _internal_has_node_id();
}
inline void AssociatedDetection::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AssociatedDetection::node_id() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AssociatedDetection::set_node_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id)
}
inline std::string* AssociatedDetection::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id)
  return _s;
}
inline const std::string& AssociatedDetection::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void AssociatedDetection::_internal_set_node_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AssociatedDetection::_internal_mutable_node_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AssociatedDetection::release_node_id() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id)
  if (!_internal_has_node_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.node_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void AssociatedDetection::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id)
}

// optional string object_id = 3 [(.sapient_msg.field_options) = {
inline bool AssociatedDetection::_internal_has_object_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AssociatedDetection::has_object_id() const {
  return _internal_has_object_id();
}
inline void AssociatedDetection::clear_object_id() {
  _impl_.object_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& AssociatedDetection::object_id() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id)
  return _internal_object_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AssociatedDetection::set_object_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.object_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id)
}
inline std::string* AssociatedDetection::mutable_object_id() {
  std::string* _s = _internal_mutable_object_id();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id)
  return _s;
}
inline const std::string& AssociatedDetection::_internal_object_id() const {
  return _impl_.object_id_.Get();
}
inline void AssociatedDetection::_internal_set_object_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.object_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AssociatedDetection::_internal_mutable_object_id() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.object_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AssociatedDetection::release_object_id() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id)
  if (!_internal_has_object_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.object_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.object_id_.IsDefault()) {
    _impl_.object_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void AssociatedDetection::set_allocated_object_id(std::string* object_id) {
  if (object_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.object_id_.SetAllocated(object_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.object_id_.IsDefault()) {
    _impl_.object_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id)
}

// optional .sapient_msg.bsi_flex_335_v2_0.AssociationRelation association_type = 4;
inline bool AssociatedDetection::_internal_has_association_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool AssociatedDetection::has_association_type() const {
  return _internal_has_association_type();
}
inline void AssociatedDetection::clear_association_type() {
  _impl_.association_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation AssociatedDetection::_internal_association_type() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation >(_impl_.association_type_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation AssociatedDetection::association_type() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.association_type)
  return _internal_association_type();
}
inline void AssociatedDetection::_internal_set_association_type(::sapient_msg::bsi_flex_335_v2_0::AssociationRelation value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.association_type_ = value;
}
inline void AssociatedDetection::set_association_type(::sapient_msg::bsi_flex_335_v2_0::AssociationRelation value) {
  _internal_set_association_type(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.association_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation>() {
  return ::sapient_msg::bsi_flex_335_v2_0::AssociationRelation_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_associated_5fdetection_2eproto
