// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: associated_detection.proto

#include "associated_detection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR AssociatedDetection::AssociatedDetection(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.node_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.object_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.association_type_)*/0} {}
struct AssociatedDetectionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AssociatedDetectionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AssociatedDetectionDefaultTypeInternal() {}
  union {
    AssociatedDetection _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AssociatedDetectionDefaultTypeInternal _AssociatedDetection_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_associated_5fdetection_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_associated_5fdetection_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_associated_5fdetection_2eproto = nullptr;

const uint32_t TableStruct_associated_5fdetection_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _impl_.node_id_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _impl_.object_id_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection, _impl_.association_type_),
  2,
  0,
  1,
  3,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_AssociatedDetection_default_instance_._instance,
};

const char descriptor_table_protodef_associated_5fdetection_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032associated_detection.proto\022\035sapient_ms"
  "g.bsi_flex_335_v2_0\032\037google/protobuf/tim"
  "estamp.proto\032\023proto_options.proto\"\233\002\n\023As"
  "sociatedDetection\0222\n\ttimestamp\030\001 \001(\0132\032.g"
  "oogle.protobuf.TimestampH\000\210\001\001\022\036\n\007node_id"
  "\030\002 \001(\tB\010\212\265\030\004\010\001\030\001H\001\210\001\001\022 \n\tobject_id\030\003 \001(\t"
  "B\010\212\265\030\004\010\001\020\001H\002\210\001\001\022Q\n\020association_type\030\004 \001("
  "\01622.sapient_msg.bsi_flex_335_v2_0.Associ"
  "ationRelationH\003\210\001\001B\014\n\n_timestampB\n\n\010_nod"
  "e_idB\014\n\n_object_idB\023\n\021_association_type*"
  "\304\001\n\023AssociationRelation\022$\n ASSOCIATION_R"
  "ELATION_UNSPECIFIED\020\000\022$\n ASSOCIATION_REL"
  "ATION_NO_RELATION\020\001\022\037\n\033ASSOCIATION_RELAT"
  "ION_PARENT\020\002\022\036\n\032ASSOCIATION_RELATION_CHI"
  "LD\020\003\022 \n\034ASSOCIATION_RELATION_SIBLING\020\004BA"
  "\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\030A"
  "ssociatedDetectionProtoP\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_associated_5fdetection_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
  &::descriptor_table_proto_5foptions_2eproto,
};
static ::_pbi::once_flag descriptor_table_associated_5fdetection_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_associated_5fdetection_2eproto = {
    false, false, 673, descriptor_table_protodef_associated_5fdetection_2eproto,
    "associated_detection.proto",
    &descriptor_table_associated_5fdetection_2eproto_once, descriptor_table_associated_5fdetection_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_associated_5fdetection_2eproto::offsets,
    file_level_metadata_associated_5fdetection_2eproto, file_level_enum_descriptors_associated_5fdetection_2eproto,
    file_level_service_descriptors_associated_5fdetection_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_associated_5fdetection_2eproto_getter() {
  return &descriptor_table_associated_5fdetection_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_associated_5fdetection_2eproto(&descriptor_table_associated_5fdetection_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AssociationRelation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_associated_5fdetection_2eproto);
  return file_level_enum_descriptors_associated_5fdetection_2eproto[0];
}
bool AssociationRelation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class AssociatedDetection::_Internal {
 public:
  using HasBits = decltype(std::declval<AssociatedDetection>()._impl_._has_bits_);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const AssociatedDetection* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_node_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_object_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_association_type(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
AssociatedDetection::_Internal::timestamp(const AssociatedDetection* msg) {
  return *msg->_impl_.timestamp_;
}
void AssociatedDetection::clear_timestamp() {
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
AssociatedDetection::AssociatedDetection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
}
AssociatedDetection::AssociatedDetection(const AssociatedDetection& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AssociatedDetection* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.node_id_){}
    , decltype(_impl_.object_id_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.association_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_node_id()) {
    _this->_impl_.node_id_.Set(from._internal_node_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.object_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.object_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_object_id()) {
    _this->_impl_.object_id_.Set(from._internal_object_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  _this->_impl_.association_type_ = from._impl_.association_type_;
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
}

inline void AssociatedDetection::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.node_id_){}
    , decltype(_impl_.object_id_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.association_type_){0}
  };
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.object_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.object_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AssociatedDetection::~AssociatedDetection() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AssociatedDetection::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_id_.Destroy();
  _impl_.object_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
}

void AssociatedDetection::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AssociatedDetection::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.node_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.object_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
  }
  _impl_.association_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AssociatedDetection::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string node_id = 2 [(.sapient_msg.field_options) = {
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id"));
        } else
          goto handle_unusual;
        continue;
      // optional string object_id = 3 [(.sapient_msg.field_options) = {
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_object_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id"));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.AssociationRelation association_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_association_type(static_cast<::sapient_msg::bsi_flex_335_v2_0::AssociationRelation>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AssociatedDetection::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .google.protobuf.Timestamp timestamp = 1;
  if (_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // optional string node_id = 2 [(.sapient_msg.field_options) = {
  if (_internal_has_node_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.node_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_node_id(), target);
  }

  // optional string object_id = 3 [(.sapient_msg.field_options) = {
  if (_internal_has_object_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_object_id().data(), static_cast<int>(this->_internal_object_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.object_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_object_id(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.AssociationRelation association_type = 4;
  if (_internal_has_association_type()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_association_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  return target;
}

size_t AssociatedDetection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string node_id = 2 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_node_id());
    }

    // optional string object_id = 3 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_object_id());
    }

    // optional .google.protobuf.Timestamp timestamp = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.timestamp_);
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.AssociationRelation association_type = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_association_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AssociatedDetection::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AssociatedDetection::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AssociatedDetection::GetClassData() const { return &_class_data_; }


void AssociatedDetection::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AssociatedDetection*>(&to_msg);
  auto& from = static_cast<const AssociatedDetection&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_node_id(from._internal_node_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_object_id(from._internal_object_id());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_timestamp());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.association_type_ = from._impl_.association_type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AssociatedDetection::CopyFrom(const AssociatedDetection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.AssociatedDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AssociatedDetection::IsInitialized() const {
  return true;
}

void AssociatedDetection::InternalSwap(AssociatedDetection* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.node_id_, lhs_arena,
      &other->_impl_.node_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.object_id_, lhs_arena,
      &other->_impl_.object_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AssociatedDetection, _impl_.association_type_)
      + sizeof(AssociatedDetection::_impl_.association_type_)
      - PROTOBUF_FIELD_OFFSET(AssociatedDetection, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AssociatedDetection::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_associated_5fdetection_2eproto_getter, &descriptor_table_associated_5fdetection_2eproto_once,
      file_level_metadata_associated_5fdetection_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::AssociatedDetection >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
