// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_error_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_error_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_error_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_error_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_error_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class Error;
struct ErrorDefaultTypeInternal;
extern ErrorDefaultTypeInternal _Error_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::Error* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::Error>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class Error final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.Error) */ {
 public:
  inline Error() : Error(nullptr) {}
  ~Error() override;
  explicit PROTOBUF_CONSTEXPR Error(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Error(const Error& from);
  Error(Error&& from) noexcept
    : Error() {
    *this = ::std::move(from);
  }

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline Error& operator=(Error&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Error& default_instance() {
    return *internal_default_instance();
  }
  static inline const Error* internal_default_instance() {
    return reinterpret_cast<const Error*>(
               &_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Error& a, Error& b) {
    a.Swap(&b);
  }
  inline void Swap(Error* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Error* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Error>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Error& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Error& from) {
    Error::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Error* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.Error";
  }
  protected:
  explicit Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 3,
    kPacketFieldNumber = 1,
  };
  // repeated string error_message = 3 [(.sapient_msg.field_options) = {
  int error_message_size() const;
  private:
  int _internal_error_message_size() const;
  public:
  void clear_error_message();
  const std::string& error_message(int index) const;
  std::string* mutable_error_message(int index);
  void set_error_message(int index, const std::string& value);
  void set_error_message(int index, std::string&& value);
  void set_error_message(int index, const char* value);
  void set_error_message(int index, const char* value, size_t size);
  std::string* add_error_message();
  void add_error_message(const std::string& value);
  void add_error_message(std::string&& value);
  void add_error_message(const char* value);
  void add_error_message(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& error_message() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_error_message();
  private:
  const std::string& _internal_error_message(int index) const;
  std::string* _internal_add_error_message();
  public:

  // optional bytes packet = 1 [(.sapient_msg.field_options) = {
  bool has_packet() const;
  private:
  bool _internal_has_packet() const;
  public:
  void clear_packet();
  const std::string& packet() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_packet(ArgT0&& arg0, ArgT... args);
  std::string* mutable_packet();
  PROTOBUF_NODISCARD std::string* release_packet();
  void set_allocated_packet(std::string* packet);
  private:
  const std::string& _internal_packet() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_packet(const std::string& value);
  std::string* _internal_mutable_packet();
  public:

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.Error)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> error_message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr packet_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_error_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Error

// optional bytes packet = 1 [(.sapient_msg.field_options) = {
inline bool Error::_internal_has_packet() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Error::has_packet() const {
  return _internal_has_packet();
}
inline void Error::clear_packet() {
  _impl_.packet_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Error::packet() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Error.packet)
  return _internal_packet();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_packet(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.packet_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Error.packet)
}
inline std::string* Error::mutable_packet() {
  std::string* _s = _internal_mutable_packet();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Error.packet)
  return _s;
}
inline const std::string& Error::_internal_packet() const {
  return _impl_.packet_.Get();
}
inline void Error::_internal_set_packet(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.packet_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_packet() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.packet_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_packet() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Error.packet)
  if (!_internal_has_packet()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.packet_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.packet_.IsDefault()) {
    _impl_.packet_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Error::set_allocated_packet(std::string* packet) {
  if (packet != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.packet_.SetAllocated(packet, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.packet_.IsDefault()) {
    _impl_.packet_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Error.packet)
}

// repeated string error_message = 3 [(.sapient_msg.field_options) = {
inline int Error::_internal_error_message_size() const {
  return _impl_.error_message_.size();
}
inline int Error::error_message_size() const {
  return _internal_error_message_size();
}
inline void Error::clear_error_message() {
  _impl_.error_message_.Clear();
}
inline std::string* Error::add_error_message() {
  std::string* _s = _internal_add_error_message();
  // @@protoc_insertion_point(field_add_mutable:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
  return _s;
}
inline const std::string& Error::_internal_error_message(int index) const {
  return _impl_.error_message_.Get(index);
}
inline const std::string& Error::error_message(int index) const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
  return _internal_error_message(index);
}
inline std::string* Error::mutable_error_message(int index) {
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
  return _impl_.error_message_.Mutable(index);
}
inline void Error::set_error_message(int index, const std::string& value) {
  _impl_.error_message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::set_error_message(int index, std::string&& value) {
  _impl_.error_message_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::set_error_message(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.error_message_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::set_error_message(int index, const char* value, size_t size) {
  _impl_.error_message_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline std::string* Error::_internal_add_error_message() {
  return _impl_.error_message_.Add();
}
inline void Error::add_error_message(const std::string& value) {
  _impl_.error_message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::add_error_message(std::string&& value) {
  _impl_.error_message_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::add_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.error_message_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline void Error::add_error_message(const char* value, size_t size) {
  _impl_.error_message_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Error::error_message() const {
  // @@protoc_insertion_point(field_list:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
  return _impl_.error_message_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Error::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable_list:sapient_msg.bsi_flex_335_v2_0.Error.error_message)
  return &_impl_.error_message_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_error_2eproto
