// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_follow_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_follow_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_follow_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_follow_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_follow_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class FollowObject;
struct FollowObjectDefaultTypeInternal;
extern FollowObjectDefaultTypeInternal _FollowObject_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::FollowObject* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::FollowObject>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class FollowObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.FollowObject) */ {
 public:
  inline FollowObject() : FollowObject(nullptr) {}
  ~FollowObject() override;
  explicit PROTOBUF_CONSTEXPR FollowObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FollowObject(const FollowObject& from);
  FollowObject(FollowObject&& from) noexcept
    : FollowObject() {
    *this = ::std::move(from);
  }

  inline FollowObject& operator=(const FollowObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline FollowObject& operator=(FollowObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FollowObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const FollowObject* internal_default_instance() {
    return reinterpret_cast<const FollowObject*>(
               &_FollowObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FollowObject& a, FollowObject& b) {
    a.Swap(&b);
  }
  inline void Swap(FollowObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FollowObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FollowObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FollowObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FollowObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FollowObject& from) {
    FollowObject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FollowObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.FollowObject";
  }
  protected:
  explicit FollowObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFollowObjectIdFieldNumber = 1,
  };
  // string follow_object_id = 1 [(.sapient_msg.field_options) = {
  void clear_follow_object_id();
  const std::string& follow_object_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_follow_object_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_follow_object_id();
  PROTOBUF_NODISCARD std::string* release_follow_object_id();
  void set_allocated_follow_object_id(std::string* follow_object_id);
  private:
  const std::string& _internal_follow_object_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_follow_object_id(const std::string& value);
  std::string* _internal_mutable_follow_object_id();
  public:

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.FollowObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr follow_object_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_follow_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FollowObject

// string follow_object_id = 1 [(.sapient_msg.field_options) = {
inline void FollowObject::clear_follow_object_id() {
  _impl_.follow_object_id_.ClearToEmpty();
}
inline const std::string& FollowObject::follow_object_id() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.FollowObject.follow_object_id)
  return _internal_follow_object_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FollowObject::set_follow_object_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.follow_object_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.FollowObject.follow_object_id)
}
inline std::string* FollowObject::mutable_follow_object_id() {
  std::string* _s = _internal_mutable_follow_object_id();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.FollowObject.follow_object_id)
  return _s;
}
inline const std::string& FollowObject::_internal_follow_object_id() const {
  return _impl_.follow_object_id_.Get();
}
inline void FollowObject::_internal_set_follow_object_id(const std::string& value) {
  
  _impl_.follow_object_id_.Set(value, GetArenaForAllocation());
}
inline std::string* FollowObject::_internal_mutable_follow_object_id() {
  
  return _impl_.follow_object_id_.Mutable(GetArenaForAllocation());
}
inline std::string* FollowObject::release_follow_object_id() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.FollowObject.follow_object_id)
  return _impl_.follow_object_id_.Release();
}
inline void FollowObject::set_allocated_follow_object_id(std::string* follow_object_id) {
  if (follow_object_id != nullptr) {
    
  } else {
    
  }
  _impl_.follow_object_id_.SetAllocated(follow_object_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.follow_object_id_.IsDefault()) {
    _impl_.follow_object_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.FollowObject.follow_object_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_follow_2eproto
