// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_location_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_location_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_location_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_location_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_location_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class Location;
struct LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
class LocationList;
struct LocationListDefaultTypeInternal;
extern LocationListDefaultTypeInternal _LocationList_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::Location* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::Location>(Arena*);
template<> ::sapient_msg::bsi_flex_335_v2_0::LocationList* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::LocationList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

enum LocationCoordinateSystem : int {
  LOCATION_COORDINATE_SYSTEM_UNSPECIFIED = 0,
  LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M = 1,
  LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M = 2,
  LOCATION_COORDINATE_SYSTEM_UTM_M = 5,
  LocationCoordinateSystem_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LocationCoordinateSystem_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LocationCoordinateSystem_IsValid(int value);
constexpr LocationCoordinateSystem LocationCoordinateSystem_MIN = LOCATION_COORDINATE_SYSTEM_UNSPECIFIED;
constexpr LocationCoordinateSystem LocationCoordinateSystem_MAX = LOCATION_COORDINATE_SYSTEM_UTM_M;
constexpr int LocationCoordinateSystem_ARRAYSIZE = LocationCoordinateSystem_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LocationCoordinateSystem_descriptor();
template<typename T>
inline const std::string& LocationCoordinateSystem_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LocationCoordinateSystem>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LocationCoordinateSystem_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LocationCoordinateSystem_descriptor(), enum_t_value);
}
inline bool LocationCoordinateSystem_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LocationCoordinateSystem* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LocationCoordinateSystem>(
    LocationCoordinateSystem_descriptor(), name, value);
}
enum LocationDatum : int {
  LOCATION_DATUM_UNSPECIFIED = 0,
  LOCATION_DATUM_WGS84_E = 1,
  LOCATION_DATUM_WGS84_G = 2,
  LocationDatum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LocationDatum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LocationDatum_IsValid(int value);
constexpr LocationDatum LocationDatum_MIN = LOCATION_DATUM_UNSPECIFIED;
constexpr LocationDatum LocationDatum_MAX = LOCATION_DATUM_WGS84_G;
constexpr int LocationDatum_ARRAYSIZE = LocationDatum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LocationDatum_descriptor();
template<typename T>
inline const std::string& LocationDatum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LocationDatum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LocationDatum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LocationDatum_descriptor(), enum_t_value);
}
inline bool LocationDatum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LocationDatum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LocationDatum>(
    LocationDatum_descriptor(), name, value);
}
// ===================================================================

class LocationList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.LocationList) */ {
 public:
  inline LocationList() : LocationList(nullptr) {}
  ~LocationList() override;
  explicit PROTOBUF_CONSTEXPR LocationList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LocationList(const LocationList& from);
  LocationList(LocationList&& from) noexcept
    : LocationList() {
    *this = ::std::move(from);
  }

  inline LocationList& operator=(const LocationList& from) {
    CopyFrom(from);
    return *this;
  }
  inline LocationList& operator=(LocationList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LocationList& default_instance() {
    return *internal_default_instance();
  }
  static inline const LocationList* internal_default_instance() {
    return reinterpret_cast<const LocationList*>(
               &_LocationList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LocationList& a, LocationList& b) {
    a.Swap(&b);
  }
  inline void Swap(LocationList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LocationList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LocationList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LocationList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LocationList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LocationList& from) {
    LocationList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LocationList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.LocationList";
  }
  protected:
  explicit LocationList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocationsFieldNumber = 1,
  };
  // repeated .sapient_msg.bsi_flex_335_v2_0.Location locations = 1 [(.sapient_msg.field_options) = {
  int locations_size() const;
  private:
  int _internal_locations_size() const;
  public:
  void clear_locations();
  ::sapient_msg::bsi_flex_335_v2_0::Location* mutable_locations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::Location >*
      mutable_locations();
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::Location& _internal_locations(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::Location* _internal_add_locations();
  public:
  const ::sapient_msg::bsi_flex_335_v2_0::Location& locations(int index) const;
  ::sapient_msg::bsi_flex_335_v2_0::Location* add_locations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::Location >&
      locations() const;

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.LocationList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::Location > locations_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_location_2eproto;
};
// -------------------------------------------------------------------

class Location final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.Location) */ {
 public:
  inline Location() : Location(nullptr) {}
  ~Location() override;
  explicit PROTOBUF_CONSTEXPR Location(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Location(const Location& from);
  Location(Location&& from) noexcept
    : Location() {
    *this = ::std::move(from);
  }

  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline Location& operator=(Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const Location* internal_default_instance() {
    return reinterpret_cast<const Location*>(
               &_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Location& a, Location& b) {
    a.Swap(&b);
  }
  inline void Swap(Location* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Location>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Location& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Location& from) {
    Location::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Location* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.Location";
  }
  protected:
  explicit Location(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUtmZoneFieldNumber = 9,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kXErrorFieldNumber = 4,
    kYErrorFieldNumber = 5,
    kZErrorFieldNumber = 6,
    kCoordinateSystemFieldNumber = 7,
    kDatumFieldNumber = 8,
  };
  // optional string utm_zone = 9;
  bool has_utm_zone() const;
  private:
  bool _internal_has_utm_zone() const;
  public:
  void clear_utm_zone();
  const std::string& utm_zone() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_utm_zone(ArgT0&& arg0, ArgT... args);
  std::string* mutable_utm_zone();
  PROTOBUF_NODISCARD std::string* release_utm_zone();
  void set_allocated_utm_zone(std::string* utm_zone);
  private:
  const std::string& _internal_utm_zone() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_utm_zone(const std::string& value);
  std::string* _internal_mutable_utm_zone();
  public:

  // optional double x = 1 [(.sapient_msg.field_options) = {
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // optional double y = 2 [(.sapient_msg.field_options) = {
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // optional double z = 3;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // optional double x_error = 4;
  bool has_x_error() const;
  private:
  bool _internal_has_x_error() const;
  public:
  void clear_x_error();
  double x_error() const;
  void set_x_error(double value);
  private:
  double _internal_x_error() const;
  void _internal_set_x_error(double value);
  public:

  // optional double y_error = 5;
  bool has_y_error() const;
  private:
  bool _internal_has_y_error() const;
  public:
  void clear_y_error();
  double y_error() const;
  void set_y_error(double value);
  private:
  double _internal_y_error() const;
  void _internal_set_y_error(double value);
  public:

  // optional double z_error = 6;
  bool has_z_error() const;
  private:
  bool _internal_has_z_error() const;
  public:
  void clear_z_error();
  double z_error() const;
  void set_z_error(double value);
  private:
  double _internal_z_error() const;
  void _internal_set_z_error(double value);
  public:

  // optional .sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystem coordinate_system = 7 [(.sapient_msg.field_options) = {
  bool has_coordinate_system() const;
  private:
  bool _internal_has_coordinate_system() const;
  public:
  void clear_coordinate_system();
  ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem coordinate_system() const;
  void set_coordinate_system(::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem _internal_coordinate_system() const;
  void _internal_set_coordinate_system(::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem value);
  public:

  // optional .sapient_msg.bsi_flex_335_v2_0.LocationDatum datum = 8 [(.sapient_msg.field_options) = {
  bool has_datum() const;
  private:
  bool _internal_has_datum() const;
  public:
  void clear_datum();
  ::sapient_msg::bsi_flex_335_v2_0::LocationDatum datum() const;
  void set_datum(::sapient_msg::bsi_flex_335_v2_0::LocationDatum value);
  private:
  ::sapient_msg::bsi_flex_335_v2_0::LocationDatum _internal_datum() const;
  void _internal_set_datum(::sapient_msg::bsi_flex_335_v2_0::LocationDatum value);
  public:

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr utm_zone_;
    double x_;
    double y_;
    double z_;
    double x_error_;
    double y_error_;
    double z_error_;
    int coordinate_system_;
    int datum_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_location_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LocationList

// repeated .sapient_msg.bsi_flex_335_v2_0.Location locations = 1 [(.sapient_msg.field_options) = {
inline int LocationList::_internal_locations_size() const {
  return _impl_.locations_.size();
}
inline int LocationList::locations_size() const {
  return _internal_locations_size();
}
inline void LocationList::clear_locations() {
  _impl_.locations_.Clear();
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* LocationList::mutable_locations(int index) {
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.LocationList.locations)
  return _impl_.locations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::Location >*
LocationList::mutable_locations() {
  // @@protoc_insertion_point(field_mutable_list:sapient_msg.bsi_flex_335_v2_0.LocationList.locations)
  return &_impl_.locations_;
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Location& LocationList::_internal_locations(int index) const {
  return _impl_.locations_.Get(index);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Location& LocationList::locations(int index) const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.LocationList.locations)
  return _internal_locations(index);
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* LocationList::_internal_add_locations() {
  return _impl_.locations_.Add();
}
inline ::sapient_msg::bsi_flex_335_v2_0::Location* LocationList::add_locations() {
  ::sapient_msg::bsi_flex_335_v2_0::Location* _add = _internal_add_locations();
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.LocationList.locations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sapient_msg::bsi_flex_335_v2_0::Location >&
LocationList::locations() const {
  // @@protoc_insertion_point(field_list:sapient_msg.bsi_flex_335_v2_0.LocationList.locations)
  return _impl_.locations_;
}

// -------------------------------------------------------------------

// Location

// optional double x = 1 [(.sapient_msg.field_options) = {
inline bool Location::_internal_has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Location::has_x() const {
  return _internal_has_x();
}
inline void Location::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double Location::_internal_x() const {
  return _impl_.x_;
}
inline double Location::x() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.x)
  return _internal_x();
}
inline void Location::_internal_set_x(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.x_ = value;
}
inline void Location::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.x)
}

// optional double y = 2 [(.sapient_msg.field_options) = {
inline bool Location::_internal_has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Location::has_y() const {
  return _internal_has_y();
}
inline void Location::clear_y() {
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double Location::_internal_y() const {
  return _impl_.y_;
}
inline double Location::y() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.y)
  return _internal_y();
}
inline void Location::_internal_set_y(double value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.y_ = value;
}
inline void Location::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.y)
}

// optional double z = 3;
inline bool Location::_internal_has_z() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Location::has_z() const {
  return _internal_has_z();
}
inline void Location::clear_z() {
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline double Location::_internal_z() const {
  return _impl_.z_;
}
inline double Location::z() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.z)
  return _internal_z();
}
inline void Location::_internal_set_z(double value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.z_ = value;
}
inline void Location::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.z)
}

// optional double x_error = 4;
inline bool Location::_internal_has_x_error() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Location::has_x_error() const {
  return _internal_has_x_error();
}
inline void Location::clear_x_error() {
  _impl_.x_error_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline double Location::_internal_x_error() const {
  return _impl_.x_error_;
}
inline double Location::x_error() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.x_error)
  return _internal_x_error();
}
inline void Location::_internal_set_x_error(double value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.x_error_ = value;
}
inline void Location::set_x_error(double value) {
  _internal_set_x_error(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.x_error)
}

// optional double y_error = 5;
inline bool Location::_internal_has_y_error() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Location::has_y_error() const {
  return _internal_has_y_error();
}
inline void Location::clear_y_error() {
  _impl_.y_error_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline double Location::_internal_y_error() const {
  return _impl_.y_error_;
}
inline double Location::y_error() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.y_error)
  return _internal_y_error();
}
inline void Location::_internal_set_y_error(double value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.y_error_ = value;
}
inline void Location::set_y_error(double value) {
  _internal_set_y_error(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.y_error)
}

// optional double z_error = 6;
inline bool Location::_internal_has_z_error() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Location::has_z_error() const {
  return _internal_has_z_error();
}
inline void Location::clear_z_error() {
  _impl_.z_error_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double Location::_internal_z_error() const {
  return _impl_.z_error_;
}
inline double Location::z_error() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.z_error)
  return _internal_z_error();
}
inline void Location::_internal_set_z_error(double value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.z_error_ = value;
}
inline void Location::set_z_error(double value) {
  _internal_set_z_error(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.z_error)
}

// optional .sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystem coordinate_system = 7 [(.sapient_msg.field_options) = {
inline bool Location::_internal_has_coordinate_system() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Location::has_coordinate_system() const {
  return _internal_has_coordinate_system();
}
inline void Location::clear_coordinate_system() {
  _impl_.coordinate_system_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem Location::_internal_coordinate_system() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem >(_impl_.coordinate_system_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem Location::coordinate_system() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.coordinate_system)
  return _internal_coordinate_system();
}
inline void Location::_internal_set_coordinate_system(::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.coordinate_system_ = value;
}
inline void Location::set_coordinate_system(::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem value) {
  _internal_set_coordinate_system(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.coordinate_system)
}

// optional .sapient_msg.bsi_flex_335_v2_0.LocationDatum datum = 8 [(.sapient_msg.field_options) = {
inline bool Location::_internal_has_datum() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Location::has_datum() const {
  return _internal_has_datum();
}
inline void Location::clear_datum() {
  _impl_.datum_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::sapient_msg::bsi_flex_335_v2_0::LocationDatum Location::_internal_datum() const {
  return static_cast< ::sapient_msg::bsi_flex_335_v2_0::LocationDatum >(_impl_.datum_);
}
inline ::sapient_msg::bsi_flex_335_v2_0::LocationDatum Location::datum() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.datum)
  return _internal_datum();
}
inline void Location::_internal_set_datum(::sapient_msg::bsi_flex_335_v2_0::LocationDatum value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.datum_ = value;
}
inline void Location::set_datum(::sapient_msg::bsi_flex_335_v2_0::LocationDatum value) {
  _internal_set_datum(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.datum)
}

// optional string utm_zone = 9;
inline bool Location::_internal_has_utm_zone() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Location::has_utm_zone() const {
  return _internal_has_utm_zone();
}
inline void Location::clear_utm_zone() {
  _impl_.utm_zone_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Location::utm_zone() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.Location.utm_zone)
  return _internal_utm_zone();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Location::set_utm_zone(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.utm_zone_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.Location.utm_zone)
}
inline std::string* Location::mutable_utm_zone() {
  std::string* _s = _internal_mutable_utm_zone();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.Location.utm_zone)
  return _s;
}
inline const std::string& Location::_internal_utm_zone() const {
  return _impl_.utm_zone_.Get();
}
inline void Location::_internal_set_utm_zone(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.utm_zone_.Set(value, GetArenaForAllocation());
}
inline std::string* Location::_internal_mutable_utm_zone() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.utm_zone_.Mutable(GetArenaForAllocation());
}
inline std::string* Location::release_utm_zone() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.Location.utm_zone)
  if (!_internal_has_utm_zone()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.utm_zone_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.utm_zone_.IsDefault()) {
    _impl_.utm_zone_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Location::set_allocated_utm_zone(std::string* utm_zone) {
  if (utm_zone != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.utm_zone_.SetAllocated(utm_zone, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.utm_zone_.IsDefault()) {
    _impl_.utm_zone_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.Location.utm_zone)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem>() {
  return ::sapient_msg::bsi_flex_335_v2_0::LocationCoordinateSystem_descriptor();
}
template <> struct is_proto_enum< ::sapient_msg::bsi_flex_335_v2_0::LocationDatum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sapient_msg::bsi_flex_335_v2_0::LocationDatum>() {
  return ::sapient_msg::bsi_flex_335_v2_0::LocationDatum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_location_2eproto
