// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: range_bearing.proto

#include "range_bearing.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR RangeBearing::RangeBearing(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.elevation_)*/0
  , /*decltype(_impl_.azimuth_)*/0
  , /*decltype(_impl_.range_)*/0
  , /*decltype(_impl_.elevation_error_)*/0
  , /*decltype(_impl_.azimuth_error_)*/0
  , /*decltype(_impl_.range_error_)*/0
  , /*decltype(_impl_.coordinate_system_)*/0
  , /*decltype(_impl_.datum_)*/0} {}
struct RangeBearingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RangeBearingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RangeBearingDefaultTypeInternal() {}
  union {
    RangeBearing _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RangeBearingDefaultTypeInternal _RangeBearing_default_instance_;
PROTOBUF_CONSTEXPR RangeBearingCone::RangeBearingCone(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.elevation_)*/0
  , /*decltype(_impl_.azimuth_)*/0
  , /*decltype(_impl_.range_)*/0
  , /*decltype(_impl_.horizontal_extent_)*/0
  , /*decltype(_impl_.vertical_extent_)*/0
  , /*decltype(_impl_.horizontal_extent_error_)*/0
  , /*decltype(_impl_.vertical_extent_error_)*/0
  , /*decltype(_impl_.elevation_error_)*/0
  , /*decltype(_impl_.azimuth_error_)*/0
  , /*decltype(_impl_.range_error_)*/0
  , /*decltype(_impl_.coordinate_system_)*/0
  , /*decltype(_impl_.datum_)*/0} {}
struct RangeBearingConeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RangeBearingConeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RangeBearingConeDefaultTypeInternal() {}
  union {
    RangeBearingCone _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RangeBearingConeDefaultTypeInternal _RangeBearingCone_default_instance_;
PROTOBUF_CONSTEXPR LocationOrRangeBearing::LocationOrRangeBearing(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fov_oneof_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct LocationOrRangeBearingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationOrRangeBearingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationOrRangeBearingDefaultTypeInternal() {}
  union {
    LocationOrRangeBearing _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationOrRangeBearingDefaultTypeInternal _LocationOrRangeBearing_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_range_5fbearing_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_range_5fbearing_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_range_5fbearing_2eproto = nullptr;

const uint32_t TableStruct_range_5fbearing_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.elevation_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.azimuth_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.range_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.elevation_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.azimuth_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.range_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.coordinate_system_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearing, _impl_.datum_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.elevation_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.azimuth_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.range_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.horizontal_extent_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.vertical_extent_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.horizontal_extent_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.vertical_extent_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.elevation_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.azimuth_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.range_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.coordinate_system_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone, _impl_.datum_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing, _impl_.fov_oneof_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::RangeBearing)},
  { 22, 40, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone)},
  { 52, -1, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_RangeBearing_default_instance_._instance,
  &::sapient_msg::bsi_flex_335_v2_0::_RangeBearingCone_default_instance_._instance,
  &::sapient_msg::bsi_flex_335_v2_0::_LocationOrRangeBearing_default_instance_._instance,
};

const char descriptor_table_protodef_range_5fbearing_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023range_bearing.proto\022\035sapient_msg.bsi_f"
  "lex_335_v2_0\032\016location.proto\032\023proto_opti"
  "ons.proto\"\321\003\n\014RangeBearing\022\026\n\televation\030"
  "\001 \001(\001H\000\210\001\001\022\024\n\007azimuth\030\002 \001(\001H\001\210\001\001\022\022\n\005rang"
  "e\030\003 \001(\001H\002\210\001\001\022\034\n\017elevation_error\030\004 \001(\001H\003\210"
  "\001\001\022\032\n\razimuth_error\030\005 \001(\001H\004\210\001\001\022\030\n\013range_"
  "error\030\006 \001(\001H\005\210\001\001\022c\n\021coordinate_system\030\007 "
  "\001(\0162;.sapient_msg.bsi_flex_335_v2_0.Rang"
  "eBearingCoordinateSystemB\006\212\265\030\002\010\001H\006\210\001\001\022L\n"
  "\005datum\030\010 \001(\01620.sapient_msg.bsi_flex_335_"
  "v2_0.RangeBearingDatumB\006\212\265\030\002\010\001H\007\210\001\001B\014\n\n_"
  "elevationB\n\n\010_azimuthB\010\n\006_rangeB\022\n\020_elev"
  "ation_errorB\020\n\016_azimuth_errorB\016\n\014_range_"
  "errorB\024\n\022_coordinate_systemB\010\n\006_datum\"\275\005"
  "\n\020RangeBearingCone\022\026\n\televation\030\001 \001(\001H\000\210"
  "\001\001\022\024\n\007azimuth\030\002 \001(\001H\001\210\001\001\022\022\n\005range\030\003 \001(\001H"
  "\002\210\001\001\022\036\n\021horizontal_extent\030\004 \001(\001H\003\210\001\001\022\034\n\017"
  "vertical_extent\030\005 \001(\001H\004\210\001\001\022$\n\027horizontal"
  "_extent_error\030\006 \001(\001H\005\210\001\001\022\"\n\025vertical_ext"
  "ent_error\030\007 \001(\001H\006\210\001\001\022\034\n\017elevation_error\030"
  "\010 \001(\001H\007\210\001\001\022\032\n\razimuth_error\030\t \001(\001H\010\210\001\001\022\030"
  "\n\013range_error\030\n \001(\001H\t\210\001\001\022c\n\021coordinate_s"
  "ystem\030\013 \001(\0162;.sapient_msg.bsi_flex_335_v"
  "2_0.RangeBearingCoordinateSystemB\006\212\265\030\002\010\001"
  "H\n\210\001\001\022L\n\005datum\030\014 \001(\01620.sapient_msg.bsi_f"
  "lex_335_v2_0.RangeBearingDatumB\006\212\265\030\002\010\001H\013"
  "\210\001\001B\014\n\n_elevationB\n\n\010_azimuthB\010\n\006_rangeB"
  "\024\n\022_horizontal_extentB\022\n\020_vertical_exten"
  "tB\032\n\030_horizontal_extent_errorB\030\n\026_vertic"
  "al_extent_errorB\022\n\020_elevation_errorB\020\n\016_"
  "azimuth_errorB\016\n\014_range_errorB\024\n\022_coordi"
  "nate_systemB\010\n\006_datum\"\275\001\n\026LocationOrRang"
  "eBearing\022H\n\rrange_bearing\030\001 \001(\0132/.sapien"
  "t_msg.bsi_flex_335_v2_0.RangeBearingCone"
  "H\000\022D\n\rlocation_list\030\002 \001(\0132+.sapient_msg."
  "bsi_flex_335_v2_0.LocationListH\000B\023\n\tfov_"
  "oneof\022\006\212\265\030\002\010\001*\231\002\n\034RangeBearingCoordinate"
  "System\022/\n+RANGE_BEARING_COORDINATE_SYSTE"
  "M_UNSPECIFIED\020\000\022-\n)RANGE_BEARING_COORDIN"
  "ATE_SYSTEM_DEGREES_M\020\001\022-\n)RANGE_BEARING_"
  "COORDINATE_SYSTEM_RADIANS_M\020\002\022.\n*RANGE_B"
  "EARING_COORDINATE_SYSTEM_DEGREES_KM\020\003\022.\n"
  "*RANGE_BEARING_COORDINATE_SYSTEM_RADIANS"
  "_KM\020\004\"\004\010\005\020\005\"\004\010\006\020\006*\270\001\n\021RangeBearingDatum\022"
  "#\n\037RANGE_BEARING_DATUM_UNSPECIFIED\020\000\022\034\n\030"
  "RANGE_BEARING_DATUM_TRUE\020\001\022 \n\034RANGE_BEAR"
  "ING_DATUM_MAGNETIC\020\002\022\034\n\030RANGE_BEARING_DA"
  "TUM_GRID\020\003\022 \n\034RANGE_BEARING_DATUM_PLATFO"
  "RM\020\004B:\n#uk.gov.dstl.sapientmsg.bsiflex33"
  "5v2B\021RangeBearingProtoP\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_range_5fbearing_2eproto_deps[2] = {
  &::descriptor_table_location_2eproto,
  &::descriptor_table_proto_5foptions_2eproto,
};
static ::_pbi::once_flag descriptor_table_range_5fbearing_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_range_5fbearing_2eproto = {
    false, false, 1992, descriptor_table_protodef_range_5fbearing_2eproto,
    "range_bearing.proto",
    &descriptor_table_range_5fbearing_2eproto_once, descriptor_table_range_5fbearing_2eproto_deps, 2, 3,
    schemas, file_default_instances, TableStruct_range_5fbearing_2eproto::offsets,
    file_level_metadata_range_5fbearing_2eproto, file_level_enum_descriptors_range_5fbearing_2eproto,
    file_level_service_descriptors_range_5fbearing_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_range_5fbearing_2eproto_getter() {
  return &descriptor_table_range_5fbearing_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_range_5fbearing_2eproto(&descriptor_table_range_5fbearing_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RangeBearingCoordinateSystem_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_range_5fbearing_2eproto);
  return file_level_enum_descriptors_range_5fbearing_2eproto[0];
}
bool RangeBearingCoordinateSystem_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RangeBearingDatum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_range_5fbearing_2eproto);
  return file_level_enum_descriptors_range_5fbearing_2eproto[1];
}
bool RangeBearingDatum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class RangeBearing::_Internal {
 public:
  using HasBits = decltype(std::declval<RangeBearing>()._impl_._has_bits_);
  static void set_has_elevation(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_azimuth(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_range(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_elevation_error(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_azimuth_error(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_range_error(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_coordinate_system(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_datum(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
};

RangeBearing::RangeBearing(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
}
RangeBearing::RangeBearing(const RangeBearing& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RangeBearing* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.elevation_){}
    , decltype(_impl_.azimuth_){}
    , decltype(_impl_.range_){}
    , decltype(_impl_.elevation_error_){}
    , decltype(_impl_.azimuth_error_){}
    , decltype(_impl_.range_error_){}
    , decltype(_impl_.coordinate_system_){}
    , decltype(_impl_.datum_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.elevation_, &from._impl_.elevation_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.datum_) -
    reinterpret_cast<char*>(&_impl_.elevation_)) + sizeof(_impl_.datum_));
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
}

inline void RangeBearing::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.elevation_){0}
    , decltype(_impl_.azimuth_){0}
    , decltype(_impl_.range_){0}
    , decltype(_impl_.elevation_error_){0}
    , decltype(_impl_.azimuth_error_){0}
    , decltype(_impl_.range_error_){0}
    , decltype(_impl_.coordinate_system_){0}
    , decltype(_impl_.datum_){0}
  };
}

RangeBearing::~RangeBearing() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RangeBearing::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RangeBearing::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RangeBearing::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.elevation_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.datum_) -
        reinterpret_cast<char*>(&_impl_.elevation_)) + sizeof(_impl_.datum_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RangeBearing::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double elevation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_elevation(&has_bits);
          _impl_.elevation_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double azimuth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_azimuth(&has_bits);
          _impl_.azimuth_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double range = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_range(&has_bits);
          _impl_.range_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double elevation_error = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_elevation_error(&has_bits);
          _impl_.elevation_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double azimuth_error = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _Internal::set_has_azimuth_error(&has_bits);
          _impl_.azimuth_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double range_error = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_range_error(&has_bits);
          _impl_.range_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 7 [(.sapient_msg.field_options) = {
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_coordinate_system(static_cast<::sapient_msg::bsi_flex_335_v2_0::RangeBearingCoordinateSystem>(val));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 8 [(.sapient_msg.field_options) = {
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_datum(static_cast<::sapient_msg::bsi_flex_335_v2_0::RangeBearingDatum>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RangeBearing::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional double elevation = 1;
  if (_internal_has_elevation()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_elevation(), target);
  }

  // optional double azimuth = 2;
  if (_internal_has_azimuth()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_azimuth(), target);
  }

  // optional double range = 3;
  if (_internal_has_range()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_range(), target);
  }

  // optional double elevation_error = 4;
  if (_internal_has_elevation_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_elevation_error(), target);
  }

  // optional double azimuth_error = 5;
  if (_internal_has_azimuth_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_azimuth_error(), target);
  }

  // optional double range_error = 6;
  if (_internal_has_range_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_range_error(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 7 [(.sapient_msg.field_options) = {
  if (_internal_has_coordinate_system()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_coordinate_system(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 8 [(.sapient_msg.field_options) = {
  if (_internal_has_datum()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      8, this->_internal_datum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  return target;
}

size_t RangeBearing::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional double elevation = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional double azimuth = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional double range = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double elevation_error = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double azimuth_error = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double range_error = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 7 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_coordinate_system());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 8 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_datum());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RangeBearing::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RangeBearing::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RangeBearing::GetClassData() const { return &_class_data_; }


void RangeBearing::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RangeBearing*>(&to_msg);
  auto& from = static_cast<const RangeBearing&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.elevation_ = from._impl_.elevation_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.azimuth_ = from._impl_.azimuth_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.range_ = from._impl_.range_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.elevation_error_ = from._impl_.elevation_error_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.azimuth_error_ = from._impl_.azimuth_error_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.range_error_ = from._impl_.range_error_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.coordinate_system_ = from._impl_.coordinate_system_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.datum_ = from._impl_.datum_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RangeBearing::CopyFrom(const RangeBearing& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.RangeBearing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RangeBearing::IsInitialized() const {
  return true;
}

void RangeBearing::InternalSwap(RangeBearing* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RangeBearing, _impl_.datum_)
      + sizeof(RangeBearing::_impl_.datum_)
      - PROTOBUF_FIELD_OFFSET(RangeBearing, _impl_.elevation_)>(
          reinterpret_cast<char*>(&_impl_.elevation_),
          reinterpret_cast<char*>(&other->_impl_.elevation_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RangeBearing::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_range_5fbearing_2eproto_getter, &descriptor_table_range_5fbearing_2eproto_once,
      file_level_metadata_range_5fbearing_2eproto[0]);
}

// ===================================================================

class RangeBearingCone::_Internal {
 public:
  using HasBits = decltype(std::declval<RangeBearingCone>()._impl_._has_bits_);
  static void set_has_elevation(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_azimuth(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_range(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_horizontal_extent(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_vertical_extent(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_horizontal_extent_error(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_vertical_extent_error(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_elevation_error(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_azimuth_error(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_range_error(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_coordinate_system(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_datum(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
};

RangeBearingCone::RangeBearingCone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
}
RangeBearingCone::RangeBearingCone(const RangeBearingCone& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RangeBearingCone* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.elevation_){}
    , decltype(_impl_.azimuth_){}
    , decltype(_impl_.range_){}
    , decltype(_impl_.horizontal_extent_){}
    , decltype(_impl_.vertical_extent_){}
    , decltype(_impl_.horizontal_extent_error_){}
    , decltype(_impl_.vertical_extent_error_){}
    , decltype(_impl_.elevation_error_){}
    , decltype(_impl_.azimuth_error_){}
    , decltype(_impl_.range_error_){}
    , decltype(_impl_.coordinate_system_){}
    , decltype(_impl_.datum_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.elevation_, &from._impl_.elevation_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.datum_) -
    reinterpret_cast<char*>(&_impl_.elevation_)) + sizeof(_impl_.datum_));
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
}

inline void RangeBearingCone::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.elevation_){0}
    , decltype(_impl_.azimuth_){0}
    , decltype(_impl_.range_){0}
    , decltype(_impl_.horizontal_extent_){0}
    , decltype(_impl_.vertical_extent_){0}
    , decltype(_impl_.horizontal_extent_error_){0}
    , decltype(_impl_.vertical_extent_error_){0}
    , decltype(_impl_.elevation_error_){0}
    , decltype(_impl_.azimuth_error_){0}
    , decltype(_impl_.range_error_){0}
    , decltype(_impl_.coordinate_system_){0}
    , decltype(_impl_.datum_){0}
  };
}

RangeBearingCone::~RangeBearingCone() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RangeBearingCone::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RangeBearingCone::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RangeBearingCone::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.elevation_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.elevation_error_) -
        reinterpret_cast<char*>(&_impl_.elevation_)) + sizeof(_impl_.elevation_error_));
  }
  if (cached_has_bits & 0x00000f00u) {
    ::memset(&_impl_.azimuth_error_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.datum_) -
        reinterpret_cast<char*>(&_impl_.azimuth_error_)) + sizeof(_impl_.datum_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RangeBearingCone::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double elevation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_elevation(&has_bits);
          _impl_.elevation_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double azimuth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_azimuth(&has_bits);
          _impl_.azimuth_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double range = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_range(&has_bits);
          _impl_.range_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double horizontal_extent = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_horizontal_extent(&has_bits);
          _impl_.horizontal_extent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double vertical_extent = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _Internal::set_has_vertical_extent(&has_bits);
          _impl_.vertical_extent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double horizontal_extent_error = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_horizontal_extent_error(&has_bits);
          _impl_.horizontal_extent_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double vertical_extent_error = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _Internal::set_has_vertical_extent_error(&has_bits);
          _impl_.vertical_extent_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double elevation_error = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _Internal::set_has_elevation_error(&has_bits);
          _impl_.elevation_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double azimuth_error = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _Internal::set_has_azimuth_error(&has_bits);
          _impl_.azimuth_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double range_error = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _Internal::set_has_range_error(&has_bits);
          _impl_.range_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 11 [(.sapient_msg.field_options) = {
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_coordinate_system(static_cast<::sapient_msg::bsi_flex_335_v2_0::RangeBearingCoordinateSystem>(val));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 12 [(.sapient_msg.field_options) = {
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_datum(static_cast<::sapient_msg::bsi_flex_335_v2_0::RangeBearingDatum>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RangeBearingCone::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional double elevation = 1;
  if (_internal_has_elevation()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_elevation(), target);
  }

  // optional double azimuth = 2;
  if (_internal_has_azimuth()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_azimuth(), target);
  }

  // optional double range = 3;
  if (_internal_has_range()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_range(), target);
  }

  // optional double horizontal_extent = 4;
  if (_internal_has_horizontal_extent()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_horizontal_extent(), target);
  }

  // optional double vertical_extent = 5;
  if (_internal_has_vertical_extent()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_vertical_extent(), target);
  }

  // optional double horizontal_extent_error = 6;
  if (_internal_has_horizontal_extent_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_horizontal_extent_error(), target);
  }

  // optional double vertical_extent_error = 7;
  if (_internal_has_vertical_extent_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_vertical_extent_error(), target);
  }

  // optional double elevation_error = 8;
  if (_internal_has_elevation_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(8, this->_internal_elevation_error(), target);
  }

  // optional double azimuth_error = 9;
  if (_internal_has_azimuth_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_azimuth_error(), target);
  }

  // optional double range_error = 10;
  if (_internal_has_range_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(10, this->_internal_range_error(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 11 [(.sapient_msg.field_options) = {
  if (_internal_has_coordinate_system()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      11, this->_internal_coordinate_system(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 12 [(.sapient_msg.field_options) = {
  if (_internal_has_datum()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      12, this->_internal_datum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  return target;
}

size_t RangeBearingCone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional double elevation = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional double azimuth = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional double range = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double horizontal_extent = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double vertical_extent = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double horizontal_extent_error = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

    // optional double vertical_extent_error = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 8;
    }

    // optional double elevation_error = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 8;
    }

  }
  if (cached_has_bits & 0x00000f00u) {
    // optional double azimuth_error = 9;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + 8;
    }

    // optional double range_error = 10;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + 8;
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem coordinate_system = 11 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_coordinate_system());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum datum = 12 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_datum());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RangeBearingCone::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RangeBearingCone::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RangeBearingCone::GetClassData() const { return &_class_data_; }


void RangeBearingCone::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RangeBearingCone*>(&to_msg);
  auto& from = static_cast<const RangeBearingCone&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.elevation_ = from._impl_.elevation_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.azimuth_ = from._impl_.azimuth_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.range_ = from._impl_.range_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.horizontal_extent_ = from._impl_.horizontal_extent_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.vertical_extent_ = from._impl_.vertical_extent_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.horizontal_extent_error_ = from._impl_.horizontal_extent_error_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.vertical_extent_error_ = from._impl_.vertical_extent_error_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.elevation_error_ = from._impl_.elevation_error_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000f00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.azimuth_error_ = from._impl_.azimuth_error_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.range_error_ = from._impl_.range_error_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.coordinate_system_ = from._impl_.coordinate_system_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.datum_ = from._impl_.datum_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RangeBearingCone::CopyFrom(const RangeBearingCone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.RangeBearingCone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RangeBearingCone::IsInitialized() const {
  return true;
}

void RangeBearingCone::InternalSwap(RangeBearingCone* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RangeBearingCone, _impl_.datum_)
      + sizeof(RangeBearingCone::_impl_.datum_)
      - PROTOBUF_FIELD_OFFSET(RangeBearingCone, _impl_.elevation_)>(
          reinterpret_cast<char*>(&_impl_.elevation_),
          reinterpret_cast<char*>(&other->_impl_.elevation_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RangeBearingCone::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_range_5fbearing_2eproto_getter, &descriptor_table_range_5fbearing_2eproto_once,
      file_level_metadata_range_5fbearing_2eproto[1]);
}

// ===================================================================

class LocationOrRangeBearing::_Internal {
 public:
  static const ::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone& range_bearing(const LocationOrRangeBearing* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::LocationList& location_list(const LocationOrRangeBearing* msg);
};

const ::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone&
LocationOrRangeBearing::_Internal::range_bearing(const LocationOrRangeBearing* msg) {
  return *msg->_impl_.fov_oneof_.range_bearing_;
}
const ::sapient_msg::bsi_flex_335_v2_0::LocationList&
LocationOrRangeBearing::_Internal::location_list(const LocationOrRangeBearing* msg) {
  return *msg->_impl_.fov_oneof_.location_list_;
}
void LocationOrRangeBearing::set_allocated_range_bearing(::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone* range_bearing) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_fov_oneof();
  if (range_bearing) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(range_bearing);
    if (message_arena != submessage_arena) {
      range_bearing = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, range_bearing, submessage_arena);
    }
    set_has_range_bearing();
    _impl_.fov_oneof_.range_bearing_ = range_bearing;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing.range_bearing)
}
void LocationOrRangeBearing::set_allocated_location_list(::sapient_msg::bsi_flex_335_v2_0::LocationList* location_list) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_fov_oneof();
  if (location_list) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(location_list));
    if (message_arena != submessage_arena) {
      location_list = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, location_list, submessage_arena);
    }
    set_has_location_list();
    _impl_.fov_oneof_.location_list_ = location_list;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing.location_list)
}
void LocationOrRangeBearing::clear_location_list() {
  if (_internal_has_location_list()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.fov_oneof_.location_list_;
    }
    clear_has_fov_oneof();
  }
}
LocationOrRangeBearing::LocationOrRangeBearing(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
}
LocationOrRangeBearing::LocationOrRangeBearing(const LocationOrRangeBearing& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LocationOrRangeBearing* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fov_oneof_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_fov_oneof();
  switch (from.fov_oneof_case()) {
    case kRangeBearing: {
      _this->_internal_mutable_range_bearing()->::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone::MergeFrom(
          from._internal_range_bearing());
      break;
    }
    case kLocationList: {
      _this->_internal_mutable_location_list()->::sapient_msg::bsi_flex_335_v2_0::LocationList::MergeFrom(
          from._internal_location_list());
      break;
    }
    case FOV_ONEOF_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
}

inline void LocationOrRangeBearing::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fov_oneof_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_fov_oneof();
}

LocationOrRangeBearing::~LocationOrRangeBearing() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LocationOrRangeBearing::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_fov_oneof()) {
    clear_fov_oneof();
  }
}

void LocationOrRangeBearing::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LocationOrRangeBearing::clear_fov_oneof() {
// @@protoc_insertion_point(one_of_clear_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  switch (fov_oneof_case()) {
    case kRangeBearing: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.fov_oneof_.range_bearing_;
      }
      break;
    }
    case kLocationList: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.fov_oneof_.location_list_;
      }
      break;
    }
    case FOV_ONEOF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = FOV_ONEOF_NOT_SET;
}


void LocationOrRangeBearing::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_fov_oneof();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LocationOrRangeBearing::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .sapient_msg.bsi_flex_335_v2_0.RangeBearingCone range_bearing = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_range_bearing(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.LocationList location_list = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_location_list(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LocationOrRangeBearing::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .sapient_msg.bsi_flex_335_v2_0.RangeBearingCone range_bearing = 1;
  if (_internal_has_range_bearing()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::range_bearing(this),
        _Internal::range_bearing(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.LocationList location_list = 2;
  if (_internal_has_location_list()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::location_list(this),
        _Internal::location_list(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  return target;
}

size_t LocationOrRangeBearing::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (fov_oneof_case()) {
    // .sapient_msg.bsi_flex_335_v2_0.RangeBearingCone range_bearing = 1;
    case kRangeBearing: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.fov_oneof_.range_bearing_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.LocationList location_list = 2;
    case kLocationList: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.fov_oneof_.location_list_);
      break;
    }
    case FOV_ONEOF_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LocationOrRangeBearing::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LocationOrRangeBearing::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LocationOrRangeBearing::GetClassData() const { return &_class_data_; }


void LocationOrRangeBearing::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LocationOrRangeBearing*>(&to_msg);
  auto& from = static_cast<const LocationOrRangeBearing&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.fov_oneof_case()) {
    case kRangeBearing: {
      _this->_internal_mutable_range_bearing()->::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone::MergeFrom(
          from._internal_range_bearing());
      break;
    }
    case kLocationList: {
      _this->_internal_mutable_location_list()->::sapient_msg::bsi_flex_335_v2_0::LocationList::MergeFrom(
          from._internal_location_list());
      break;
    }
    case FOV_ONEOF_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LocationOrRangeBearing::CopyFrom(const LocationOrRangeBearing& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocationOrRangeBearing::IsInitialized() const {
  return true;
}

void LocationOrRangeBearing::InternalSwap(LocationOrRangeBearing* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.fov_oneof_, other->_impl_.fov_oneof_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata LocationOrRangeBearing::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_range_5fbearing_2eproto_getter, &descriptor_table_range_5fbearing_2eproto_once,
      file_level_metadata_range_5fbearing_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::RangeBearing*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::RangeBearing >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::RangeBearing >(arena);
}
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::RangeBearingCone >(arena);
}
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::LocationOrRangeBearing >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
