// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_ack.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_registration_5fack_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_registration_5fack_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_registration_5fack_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_registration_5fack_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_registration_5fack_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class RegistrationAck;
struct RegistrationAckDefaultTypeInternal;
extern RegistrationAckDefaultTypeInternal _RegistrationAck_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::RegistrationAck* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::RegistrationAck>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class RegistrationAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.RegistrationAck) */ {
 public:
  inline RegistrationAck() : RegistrationAck(nullptr) {}
  ~RegistrationAck() override;
  explicit PROTOBUF_CONSTEXPR RegistrationAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RegistrationAck(const RegistrationAck& from);
  RegistrationAck(RegistrationAck&& from) noexcept
    : RegistrationAck() {
    *this = ::std::move(from);
  }

  inline RegistrationAck& operator=(const RegistrationAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegistrationAck& operator=(RegistrationAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegistrationAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegistrationAck* internal_default_instance() {
    return reinterpret_cast<const RegistrationAck*>(
               &_RegistrationAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegistrationAck& a, RegistrationAck& b) {
    a.Swap(&b);
  }
  inline void Swap(RegistrationAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegistrationAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegistrationAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RegistrationAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RegistrationAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RegistrationAck& from) {
    RegistrationAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegistrationAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.RegistrationAck";
  }
  protected:
  explicit RegistrationAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAckResponseReasonFieldNumber = 3,
    kAcceptanceFieldNumber = 1,
  };
  // repeated string ack_response_reason = 3;
  int ack_response_reason_size() const;
  private:
  int _internal_ack_response_reason_size() const;
  public:
  void clear_ack_response_reason();
  const std::string& ack_response_reason(int index) const;
  std::string* mutable_ack_response_reason(int index);
  void set_ack_response_reason(int index, const std::string& value);
  void set_ack_response_reason(int index, std::string&& value);
  void set_ack_response_reason(int index, const char* value);
  void set_ack_response_reason(int index, const char* value, size_t size);
  std::string* add_ack_response_reason();
  void add_ack_response_reason(const std::string& value);
  void add_ack_response_reason(std::string&& value);
  void add_ack_response_reason(const char* value);
  void add_ack_response_reason(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& ack_response_reason() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_ack_response_reason();
  private:
  const std::string& _internal_ack_response_reason(int index) const;
  std::string* _internal_add_ack_response_reason();
  public:

  // optional bool acceptance = 1 [(.sapient_msg.field_options) = {
  bool has_acceptance() const;
  private:
  bool _internal_has_acceptance() const;
  public:
  void clear_acceptance();
  bool acceptance() const;
  void set_acceptance(bool value);
  private:
  bool _internal_acceptance() const;
  void _internal_set_acceptance(bool value);
  public:

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.RegistrationAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> ack_response_reason_;
    bool acceptance_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_registration_5fack_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegistrationAck

// optional bool acceptance = 1 [(.sapient_msg.field_options) = {
inline bool RegistrationAck::_internal_has_acceptance() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RegistrationAck::has_acceptance() const {
  return _internal_has_acceptance();
}
inline void RegistrationAck::clear_acceptance() {
  _impl_.acceptance_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool RegistrationAck::_internal_acceptance() const {
  return _impl_.acceptance_;
}
inline bool RegistrationAck::acceptance() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.acceptance)
  return _internal_acceptance();
}
inline void RegistrationAck::_internal_set_acceptance(bool value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.acceptance_ = value;
}
inline void RegistrationAck::set_acceptance(bool value) {
  _internal_set_acceptance(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.acceptance)
}

// repeated string ack_response_reason = 3;
inline int RegistrationAck::_internal_ack_response_reason_size() const {
  return _impl_.ack_response_reason_.size();
}
inline int RegistrationAck::ack_response_reason_size() const {
  return _internal_ack_response_reason_size();
}
inline void RegistrationAck::clear_ack_response_reason() {
  _impl_.ack_response_reason_.Clear();
}
inline std::string* RegistrationAck::add_ack_response_reason() {
  std::string* _s = _internal_add_ack_response_reason();
  // @@protoc_insertion_point(field_add_mutable:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
  return _s;
}
inline const std::string& RegistrationAck::_internal_ack_response_reason(int index) const {
  return _impl_.ack_response_reason_.Get(index);
}
inline const std::string& RegistrationAck::ack_response_reason(int index) const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
  return _internal_ack_response_reason(index);
}
inline std::string* RegistrationAck::mutable_ack_response_reason(int index) {
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
  return _impl_.ack_response_reason_.Mutable(index);
}
inline void RegistrationAck::set_ack_response_reason(int index, const std::string& value) {
  _impl_.ack_response_reason_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::set_ack_response_reason(int index, std::string&& value) {
  _impl_.ack_response_reason_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::set_ack_response_reason(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.ack_response_reason_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::set_ack_response_reason(int index, const char* value, size_t size) {
  _impl_.ack_response_reason_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline std::string* RegistrationAck::_internal_add_ack_response_reason() {
  return _impl_.ack_response_reason_.Add();
}
inline void RegistrationAck::add_ack_response_reason(const std::string& value) {
  _impl_.ack_response_reason_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::add_ack_response_reason(std::string&& value) {
  _impl_.ack_response_reason_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::add_ack_response_reason(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.ack_response_reason_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline void RegistrationAck::add_ack_response_reason(const char* value, size_t size) {
  _impl_.ack_response_reason_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
RegistrationAck::ack_response_reason() const {
  // @@protoc_insertion_point(field_list:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
  return _impl_.ack_response_reason_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
RegistrationAck::mutable_ack_response_reason() {
  // @@protoc_insertion_point(field_mutable_list:sapient_msg.bsi_flex_335_v2_0.RegistrationAck.ack_response_reason)
  return &_impl_.ack_response_reason_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_registration_5fack_2eproto
