// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sapient_message.proto

#include "sapient_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR SapientMessage::SapientMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.node_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.destination_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.additional_information_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.content_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct SapientMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SapientMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SapientMessageDefaultTypeInternal() {}
  union {
    SapientMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SapientMessageDefaultTypeInternal _SapientMessage_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_sapient_5fmessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sapient_5fmessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sapient_5fmessage_2eproto = nullptr;

const uint32_t TableStruct_sapient_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_.node_id_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_.destination_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_.additional_information_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SapientMessage, _impl_.content_),
  3,
  0,
  1,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 20, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::SapientMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_SapientMessage_default_instance_._instance,
};

const char descriptor_table_protodef_sapient_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025sapient_message.proto\022\035sapient_msg.bsi"
  "_flex_335_v2_0\032\037google/protobuf/timestam"
  "p.proto\032\013alert.proto\032\017alert_ack.proto\032\026d"
  "etection_report.proto\032\013error.proto\032\023prot"
  "o_options.proto\032\022registration.proto\032\026reg"
  "istration_ack.proto\032\023status_report.proto"
  "\032\ntask.proto\032\016task_ack.proto\"\321\006\n\016Sapient"
  "Message\022:\n\ttimestamp\030\001 \001(\0132\032.google.prot"
  "obuf.TimestampB\006\212\265\030\002\010\001H\001\210\001\001\022\036\n\007node_id\030\002"
  " \001(\tB\010\212\265\030\004\010\001\030\001H\002\210\001\001\022#\n\016destination_id\030\003 "
  "\001(\tB\006\212\265\030\002\030\001H\003\210\001\001\022C\n\014registration\030\004 \001(\0132+"
  ".sapient_msg.bsi_flex_335_v2_0.Registrat"
  "ionH\000\022J\n\020registration_ack\030\005 \001(\0132..sapien"
  "t_msg.bsi_flex_335_v2_0.RegistrationAckH"
  "\000\022D\n\rstatus_report\030\006 \001(\0132+.sapient_msg.b"
  "si_flex_335_v2_0.StatusReportH\000\022J\n\020detec"
  "tion_report\030\007 \001(\0132..sapient_msg.bsi_flex"
  "_335_v2_0.DetectionReportH\000\0223\n\004task\030\010 \001("
  "\0132#.sapient_msg.bsi_flex_335_v2_0.TaskH\000"
  "\022:\n\010task_ack\030\t \001(\0132&.sapient_msg.bsi_fle"
  "x_335_v2_0.TaskAckH\000\0225\n\005alert\030\n \001(\0132$.sa"
  "pient_msg.bsi_flex_335_v2_0.AlertH\000\022<\n\ta"
  "lert_ack\030\013 \001(\0132\'.sapient_msg.bsi_flex_33"
  "5_v2_0.AlertAckH\000\0225\n\005error\030\014 \001(\0132$.sapie"
  "nt_msg.bsi_flex_335_v2_0.ErrorH\000\022#\n\026addi"
  "tional_information\030\r \001(\tH\004\210\001\001B\021\n\007content"
  "\022\006\212\265\030\002\010\001B\014\n\n_timestampB\n\n\010_node_idB\021\n\017_d"
  "estination_idB\031\n\027_additional_information"
  "BS\n#uk.gov.dstl.sapientmsg.bsiflex335v2B"
  "\023SapientMessageProtoP\001\212\3520\023\n\021BSI_Flex_335"
  "_v2.0b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sapient_5fmessage_2eproto_deps[11] = {
  &::descriptor_table_alert_2eproto,
  &::descriptor_table_alert_5fack_2eproto,
  &::descriptor_table_detection_5freport_2eproto,
  &::descriptor_table_error_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
  &::descriptor_table_proto_5foptions_2eproto,
  &::descriptor_table_registration_2eproto,
  &::descriptor_table_registration_5fack_2eproto,
  &::descriptor_table_status_5freport_2eproto,
  &::descriptor_table_task_2eproto,
  &::descriptor_table_task_5fack_2eproto,
};
static ::_pbi::once_flag descriptor_table_sapient_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sapient_5fmessage_2eproto = {
    false, false, 1213, descriptor_table_protodef_sapient_5fmessage_2eproto,
    "sapient_message.proto",
    &descriptor_table_sapient_5fmessage_2eproto_once, descriptor_table_sapient_5fmessage_2eproto_deps, 11, 1,
    schemas, file_default_instances, TableStruct_sapient_5fmessage_2eproto::offsets,
    file_level_metadata_sapient_5fmessage_2eproto, file_level_enum_descriptors_sapient_5fmessage_2eproto,
    file_level_service_descriptors_sapient_5fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sapient_5fmessage_2eproto_getter() {
  return &descriptor_table_sapient_5fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sapient_5fmessage_2eproto(&descriptor_table_sapient_5fmessage_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class SapientMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<SapientMessage>()._impl_._has_bits_);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const SapientMessage* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_node_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_destination_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::sapient_msg::bsi_flex_335_v2_0::Registration& registration(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::RegistrationAck& registration_ack(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::StatusReport& status_report(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::DetectionReport& detection_report(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::Task& task(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::TaskAck& task_ack(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::Alert& alert(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::AlertAck& alert_ack(const SapientMessage* msg);
  static const ::sapient_msg::bsi_flex_335_v2_0::Error& error(const SapientMessage* msg);
  static void set_has_additional_information(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
SapientMessage::_Internal::timestamp(const SapientMessage* msg) {
  return *msg->_impl_.timestamp_;
}
const ::sapient_msg::bsi_flex_335_v2_0::Registration&
SapientMessage::_Internal::registration(const SapientMessage* msg) {
  return *msg->_impl_.content_.registration_;
}
const ::sapient_msg::bsi_flex_335_v2_0::RegistrationAck&
SapientMessage::_Internal::registration_ack(const SapientMessage* msg) {
  return *msg->_impl_.content_.registration_ack_;
}
const ::sapient_msg::bsi_flex_335_v2_0::StatusReport&
SapientMessage::_Internal::status_report(const SapientMessage* msg) {
  return *msg->_impl_.content_.status_report_;
}
const ::sapient_msg::bsi_flex_335_v2_0::DetectionReport&
SapientMessage::_Internal::detection_report(const SapientMessage* msg) {
  return *msg->_impl_.content_.detection_report_;
}
const ::sapient_msg::bsi_flex_335_v2_0::Task&
SapientMessage::_Internal::task(const SapientMessage* msg) {
  return *msg->_impl_.content_.task_;
}
const ::sapient_msg::bsi_flex_335_v2_0::TaskAck&
SapientMessage::_Internal::task_ack(const SapientMessage* msg) {
  return *msg->_impl_.content_.task_ack_;
}
const ::sapient_msg::bsi_flex_335_v2_0::Alert&
SapientMessage::_Internal::alert(const SapientMessage* msg) {
  return *msg->_impl_.content_.alert_;
}
const ::sapient_msg::bsi_flex_335_v2_0::AlertAck&
SapientMessage::_Internal::alert_ack(const SapientMessage* msg) {
  return *msg->_impl_.content_.alert_ack_;
}
const ::sapient_msg::bsi_flex_335_v2_0::Error&
SapientMessage::_Internal::error(const SapientMessage* msg) {
  return *msg->_impl_.content_.error_;
}
void SapientMessage::clear_timestamp() {
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void SapientMessage::set_allocated_registration(::sapient_msg::bsi_flex_335_v2_0::Registration* registration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (registration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(registration));
    if (message_arena != submessage_arena) {
      registration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, registration, submessage_arena);
    }
    set_has_registration();
    _impl_.content_.registration_ = registration;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.registration)
}
void SapientMessage::clear_registration() {
  if (_internal_has_registration()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.registration_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_registration_ack(::sapient_msg::bsi_flex_335_v2_0::RegistrationAck* registration_ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (registration_ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(registration_ack));
    if (message_arena != submessage_arena) {
      registration_ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, registration_ack, submessage_arena);
    }
    set_has_registration_ack();
    _impl_.content_.registration_ack_ = registration_ack;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.registration_ack)
}
void SapientMessage::clear_registration_ack() {
  if (_internal_has_registration_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.registration_ack_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_status_report(::sapient_msg::bsi_flex_335_v2_0::StatusReport* status_report) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (status_report) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(status_report));
    if (message_arena != submessage_arena) {
      status_report = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status_report, submessage_arena);
    }
    set_has_status_report();
    _impl_.content_.status_report_ = status_report;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.status_report)
}
void SapientMessage::clear_status_report() {
  if (_internal_has_status_report()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.status_report_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_detection_report(::sapient_msg::bsi_flex_335_v2_0::DetectionReport* detection_report) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (detection_report) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(detection_report));
    if (message_arena != submessage_arena) {
      detection_report = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, detection_report, submessage_arena);
    }
    set_has_detection_report();
    _impl_.content_.detection_report_ = detection_report;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.detection_report)
}
void SapientMessage::clear_detection_report() {
  if (_internal_has_detection_report()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.detection_report_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_task(::sapient_msg::bsi_flex_335_v2_0::Task* task) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (task) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(task));
    if (message_arena != submessage_arena) {
      task = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, task, submessage_arena);
    }
    set_has_task();
    _impl_.content_.task_ = task;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.task)
}
void SapientMessage::clear_task() {
  if (_internal_has_task()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.task_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_task_ack(::sapient_msg::bsi_flex_335_v2_0::TaskAck* task_ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (task_ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(task_ack));
    if (message_arena != submessage_arena) {
      task_ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, task_ack, submessage_arena);
    }
    set_has_task_ack();
    _impl_.content_.task_ack_ = task_ack;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.task_ack)
}
void SapientMessage::clear_task_ack() {
  if (_internal_has_task_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.task_ack_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_alert(::sapient_msg::bsi_flex_335_v2_0::Alert* alert) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (alert) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(alert));
    if (message_arena != submessage_arena) {
      alert = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, alert, submessage_arena);
    }
    set_has_alert();
    _impl_.content_.alert_ = alert;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.alert)
}
void SapientMessage::clear_alert() {
  if (_internal_has_alert()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.alert_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_alert_ack(::sapient_msg::bsi_flex_335_v2_0::AlertAck* alert_ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (alert_ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(alert_ack));
    if (message_arena != submessage_arena) {
      alert_ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, alert_ack, submessage_arena);
    }
    set_has_alert_ack();
    _impl_.content_.alert_ack_ = alert_ack;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.alert_ack)
}
void SapientMessage::clear_alert_ack() {
  if (_internal_has_alert_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.alert_ack_;
    }
    clear_has_content();
  }
}
void SapientMessage::set_allocated_error(::sapient_msg::bsi_flex_335_v2_0::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.content_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SapientMessage.error)
}
void SapientMessage::clear_error() {
  if (_internal_has_error()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.error_;
    }
    clear_has_content();
  }
}
SapientMessage::SapientMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
}
SapientMessage::SapientMessage(const SapientMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SapientMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.node_id_){}
    , decltype(_impl_.destination_id_){}
    , decltype(_impl_.additional_information_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_node_id()) {
    _this->_impl_.node_id_.Set(from._internal_node_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.destination_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.destination_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_destination_id()) {
    _this->_impl_.destination_id_.Set(from._internal_destination_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.additional_information_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_additional_information()) {
    _this->_impl_.additional_information_.Set(from._internal_additional_information(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  clear_has_content();
  switch (from.content_case()) {
    case kRegistration: {
      _this->_internal_mutable_registration()->::sapient_msg::bsi_flex_335_v2_0::Registration::MergeFrom(
          from._internal_registration());
      break;
    }
    case kRegistrationAck: {
      _this->_internal_mutable_registration_ack()->::sapient_msg::bsi_flex_335_v2_0::RegistrationAck::MergeFrom(
          from._internal_registration_ack());
      break;
    }
    case kStatusReport: {
      _this->_internal_mutable_status_report()->::sapient_msg::bsi_flex_335_v2_0::StatusReport::MergeFrom(
          from._internal_status_report());
      break;
    }
    case kDetectionReport: {
      _this->_internal_mutable_detection_report()->::sapient_msg::bsi_flex_335_v2_0::DetectionReport::MergeFrom(
          from._internal_detection_report());
      break;
    }
    case kTask: {
      _this->_internal_mutable_task()->::sapient_msg::bsi_flex_335_v2_0::Task::MergeFrom(
          from._internal_task());
      break;
    }
    case kTaskAck: {
      _this->_internal_mutable_task_ack()->::sapient_msg::bsi_flex_335_v2_0::TaskAck::MergeFrom(
          from._internal_task_ack());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::sapient_msg::bsi_flex_335_v2_0::Alert::MergeFrom(
          from._internal_alert());
      break;
    }
    case kAlertAck: {
      _this->_internal_mutable_alert_ack()->::sapient_msg::bsi_flex_335_v2_0::AlertAck::MergeFrom(
          from._internal_alert_ack());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::sapient_msg::bsi_flex_335_v2_0::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
}

inline void SapientMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.node_id_){}
    , decltype(_impl_.destination_id_){}
    , decltype(_impl_.additional_information_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.destination_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.destination_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.additional_information_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.additional_information_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_content();
}

SapientMessage::~SapientMessage() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SapientMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_id_.Destroy();
  _impl_.destination_id_.Destroy();
  _impl_.additional_information_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
  if (has_content()) {
    clear_content();
  }
}

void SapientMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SapientMessage::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  switch (content_case()) {
    case kRegistration: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.registration_;
      }
      break;
    }
    case kRegistrationAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.registration_ack_;
      }
      break;
    }
    case kStatusReport: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.status_report_;
      }
      break;
    }
    case kDetectionReport: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.detection_report_;
      }
      break;
    }
    case kTask: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.task_;
      }
      break;
    }
    case kTaskAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.task_ack_;
      }
      break;
    }
    case kAlert: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.alert_;
      }
      break;
    }
    case kAlertAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.alert_ack_;
      }
      break;
    }
    case kError: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.error_;
      }
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}


void SapientMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.node_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.destination_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.additional_information_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
  }
  clear_content();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SapientMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .google.protobuf.Timestamp timestamp = 1 [(.sapient_msg.field_options) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string node_id = 2 [(.sapient_msg.field_options) = {
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.SapientMessage.node_id"));
        } else
          goto handle_unusual;
        continue;
      // optional string destination_id = 3 [(.sapient_msg.field_options) = {
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_destination_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.SapientMessage.destination_id"));
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_registration(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.RegistrationAck registration_ack = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_registration_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.StatusReport status_report = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_status_report(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.DetectionReport detection_report = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_detection_report(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Task task = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_task(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.TaskAck task_ack = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_task_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Alert alert = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_alert(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.AlertAck alert_ack = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_alert_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Error error = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string additional_information = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_additional_information();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.SapientMessage.additional_information"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SapientMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .google.protobuf.Timestamp timestamp = 1 [(.sapient_msg.field_options) = {
  if (_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // optional string node_id = 2 [(.sapient_msg.field_options) = {
  if (_internal_has_node_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.SapientMessage.node_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_node_id(), target);
  }

  // optional string destination_id = 3 [(.sapient_msg.field_options) = {
  if (_internal_has_destination_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_destination_id().data(), static_cast<int>(this->_internal_destination_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.SapientMessage.destination_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_destination_id(), target);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 4;
  if (_internal_has_registration()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::registration(this),
        _Internal::registration(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.RegistrationAck registration_ack = 5;
  if (_internal_has_registration_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::registration_ack(this),
        _Internal::registration_ack(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.StatusReport status_report = 6;
  if (_internal_has_status_report()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::status_report(this),
        _Internal::status_report(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.DetectionReport detection_report = 7;
  if (_internal_has_detection_report()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::detection_report(this),
        _Internal::detection_report(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Task task = 8;
  if (_internal_has_task()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::task(this),
        _Internal::task(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.TaskAck task_ack = 9;
  if (_internal_has_task_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::task_ack(this),
        _Internal::task_ack(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Alert alert = 10;
  if (_internal_has_alert()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::alert(this),
        _Internal::alert(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.AlertAck alert_ack = 11;
  if (_internal_has_alert_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::alert_ack(this),
        _Internal::alert_ack(this).GetCachedSize(), target, stream);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Error error = 12;
  if (_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  // optional string additional_information = 13;
  if (_internal_has_additional_information()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_additional_information().data(), static_cast<int>(this->_internal_additional_information().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.SapientMessage.additional_information");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_additional_information(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  return target;
}

size_t SapientMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string node_id = 2 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_node_id());
    }

    // optional string destination_id = 3 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_destination_id());
    }

    // optional string additional_information = 13;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_additional_information());
    }

    // optional .google.protobuf.Timestamp timestamp = 1 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.timestamp_);
    }

  }
  switch (content_case()) {
    // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 4;
    case kRegistration: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.registration_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.RegistrationAck registration_ack = 5;
    case kRegistrationAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.registration_ack_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.StatusReport status_report = 6;
    case kStatusReport: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.status_report_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.DetectionReport detection_report = 7;
    case kDetectionReport: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.detection_report_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.Task task = 8;
    case kTask: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.task_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.TaskAck task_ack = 9;
    case kTaskAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.task_ack_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.Alert alert = 10;
    case kAlert: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.alert_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.AlertAck alert_ack = 11;
    case kAlertAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.alert_ack_);
      break;
    }
    // .sapient_msg.bsi_flex_335_v2_0.Error error = 12;
    case kError: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.error_);
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SapientMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SapientMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SapientMessage::GetClassData() const { return &_class_data_; }


void SapientMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SapientMessage*>(&to_msg);
  auto& from = static_cast<const SapientMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_node_id(from._internal_node_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_destination_id(from._internal_destination_id());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_additional_information(from._internal_additional_information());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_timestamp());
    }
  }
  switch (from.content_case()) {
    case kRegistration: {
      _this->_internal_mutable_registration()->::sapient_msg::bsi_flex_335_v2_0::Registration::MergeFrom(
          from._internal_registration());
      break;
    }
    case kRegistrationAck: {
      _this->_internal_mutable_registration_ack()->::sapient_msg::bsi_flex_335_v2_0::RegistrationAck::MergeFrom(
          from._internal_registration_ack());
      break;
    }
    case kStatusReport: {
      _this->_internal_mutable_status_report()->::sapient_msg::bsi_flex_335_v2_0::StatusReport::MergeFrom(
          from._internal_status_report());
      break;
    }
    case kDetectionReport: {
      _this->_internal_mutable_detection_report()->::sapient_msg::bsi_flex_335_v2_0::DetectionReport::MergeFrom(
          from._internal_detection_report());
      break;
    }
    case kTask: {
      _this->_internal_mutable_task()->::sapient_msg::bsi_flex_335_v2_0::Task::MergeFrom(
          from._internal_task());
      break;
    }
    case kTaskAck: {
      _this->_internal_mutable_task_ack()->::sapient_msg::bsi_flex_335_v2_0::TaskAck::MergeFrom(
          from._internal_task_ack());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::sapient_msg::bsi_flex_335_v2_0::Alert::MergeFrom(
          from._internal_alert());
      break;
    }
    case kAlertAck: {
      _this->_internal_mutable_alert_ack()->::sapient_msg::bsi_flex_335_v2_0::AlertAck::MergeFrom(
          from._internal_alert_ack());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::sapient_msg::bsi_flex_335_v2_0::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SapientMessage::CopyFrom(const SapientMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.SapientMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SapientMessage::IsInitialized() const {
  return true;
}

void SapientMessage::InternalSwap(SapientMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.node_id_, lhs_arena,
      &other->_impl_.node_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.destination_id_, lhs_arena,
      &other->_impl_.destination_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.additional_information_, lhs_arena,
      &other->_impl_.additional_information_, rhs_arena
  );
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
  swap(_impl_.content_, other->_impl_.content_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata SapientMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sapient_5fmessage_2eproto_getter, &descriptor_table_sapient_5fmessage_2eproto_once,
      file_level_metadata_sapient_5fmessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::SapientMessage*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::SapientMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::SapientMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
