// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sky_registration.proto

#include "sky_registration.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR SkyRegistrationMessage::SkyRegistrationMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nodeid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.registration_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SkyRegistrationMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkyRegistrationMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkyRegistrationMessageDefaultTypeInternal() {}
  union {
    SkyRegistrationMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkyRegistrationMessageDefaultTypeInternal _SkyRegistrationMessage_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_sky_5fregistration_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sky_5fregistration_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sky_5fregistration_2eproto = nullptr;

const uint32_t TableStruct_sky_5fregistration_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage, _impl_.nodeid_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage, _impl_.registration_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_SkyRegistrationMessage_default_instance_._instance,
};

const char descriptor_table_protodef_sky_5fregistration_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026sky_registration.proto\022\035sapient_msg.bs"
  "i_flex_335_v2_0\032\022registration.proto\"~\n\026S"
  "kyRegistrationMessage\022\021\n\ttimestamp\030\001 \001(\t"
  "\022\016\n\006nodeId\030\002 \001(\t\022A\n\014registration\030\003 \001(\0132+"
  ".sapient_msg.bsi_flex_335_v2_0.Registrat"
  "ionb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sky_5fregistration_2eproto_deps[1] = {
  &::descriptor_table_registration_2eproto,
};
static ::_pbi::once_flag descriptor_table_sky_5fregistration_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sky_5fregistration_2eproto = {
    false, false, 211, descriptor_table_protodef_sky_5fregistration_2eproto,
    "sky_registration.proto",
    &descriptor_table_sky_5fregistration_2eproto_once, descriptor_table_sky_5fregistration_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_sky_5fregistration_2eproto::offsets,
    file_level_metadata_sky_5fregistration_2eproto, file_level_enum_descriptors_sky_5fregistration_2eproto,
    file_level_service_descriptors_sky_5fregistration_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sky_5fregistration_2eproto_getter() {
  return &descriptor_table_sky_5fregistration_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sky_5fregistration_2eproto(&descriptor_table_sky_5fregistration_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class SkyRegistrationMessage::_Internal {
 public:
  static const ::sapient_msg::bsi_flex_335_v2_0::Registration& registration(const SkyRegistrationMessage* msg);
};

const ::sapient_msg::bsi_flex_335_v2_0::Registration&
SkyRegistrationMessage::_Internal::registration(const SkyRegistrationMessage* msg) {
  return *msg->_impl_.registration_;
}
void SkyRegistrationMessage::clear_registration() {
  if (GetArenaForAllocation() == nullptr && _impl_.registration_ != nullptr) {
    delete _impl_.registration_;
  }
  _impl_.registration_ = nullptr;
}
SkyRegistrationMessage::SkyRegistrationMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
}
SkyRegistrationMessage::SkyRegistrationMessage(const SkyRegistrationMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SkyRegistrationMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.timestamp_){}
    , decltype(_impl_.nodeid_){}
    , decltype(_impl_.registration_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp().empty()) {
    _this->_impl_.timestamp_.Set(from._internal_timestamp(), 
      _this->GetArenaForAllocation());
  }
  _impl_.nodeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nodeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nodeid().empty()) {
    _this->_impl_.nodeid_.Set(from._internal_nodeid(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_registration()) {
    _this->_impl_.registration_ = new ::sapient_msg::bsi_flex_335_v2_0::Registration(*from._impl_.registration_);
  }
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
}

inline void SkyRegistrationMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.timestamp_){}
    , decltype(_impl_.nodeid_){}
    , decltype(_impl_.registration_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.nodeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nodeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SkyRegistrationMessage::~SkyRegistrationMessage() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SkyRegistrationMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.timestamp_.Destroy();
  _impl_.nodeid_.Destroy();
  if (this != internal_default_instance()) delete _impl_.registration_;
}

void SkyRegistrationMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SkyRegistrationMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timestamp_.ClearToEmpty();
  _impl_.nodeid_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.registration_ != nullptr) {
    delete _impl_.registration_;
  }
  _impl_.registration_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SkyRegistrationMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp"));
        } else
          goto handle_unusual;
        continue;
      // string nodeId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_nodeid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId"));
        } else
          goto handle_unusual;
        continue;
      // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_registration(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SkyRegistrationMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string timestamp = 1;
  if (!this->_internal_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp().data(), static_cast<int>(this->_internal_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_timestamp(), target);
  }

  // string nodeId = 2;
  if (!this->_internal_nodeid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nodeid().data(), static_cast<int>(this->_internal_nodeid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_nodeid(), target);
  }

  // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 3;
  if (this->_internal_has_registration()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::registration(this),
        _Internal::registration(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  return target;
}

size_t SkyRegistrationMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string timestamp = 1;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp());
  }

  // string nodeId = 2;
  if (!this->_internal_nodeid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nodeid());
  }

  // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 3;
  if (this->_internal_has_registration()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.registration_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SkyRegistrationMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SkyRegistrationMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SkyRegistrationMessage::GetClassData() const { return &_class_data_; }


void SkyRegistrationMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SkyRegistrationMessage*>(&to_msg);
  auto& from = static_cast<const SkyRegistrationMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_nodeid().empty()) {
    _this->_internal_set_nodeid(from._internal_nodeid());
  }
  if (from._internal_has_registration()) {
    _this->_internal_mutable_registration()->::sapient_msg::bsi_flex_335_v2_0::Registration::MergeFrom(
        from._internal_registration());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SkyRegistrationMessage::CopyFrom(const SkyRegistrationMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SkyRegistrationMessage::IsInitialized() const {
  return true;
}

void SkyRegistrationMessage::InternalSwap(SkyRegistrationMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_, lhs_arena,
      &other->_impl_.timestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nodeid_, lhs_arena,
      &other->_impl_.nodeid_, rhs_arena
  );
  swap(_impl_.registration_, other->_impl_.registration_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SkyRegistrationMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sky_5fregistration_2eproto_getter, &descriptor_table_sky_5fregistration_2eproto_once,
      file_level_metadata_sky_5fregistration_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
