// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sky_registration.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sky_5fregistration_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sky_5fregistration_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "registration.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sky_5fregistration_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sky_5fregistration_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sky_5fregistration_2eproto;
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
class SkyRegistrationMessage;
struct SkyRegistrationMessageDefaultTypeInternal;
extern SkyRegistrationMessageDefaultTypeInternal _SkyRegistrationMessage_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage* Arena::CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::SkyRegistrationMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {

// ===================================================================

class SkyRegistrationMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage) */ {
 public:
  inline SkyRegistrationMessage() : SkyRegistrationMessage(nullptr) {}
  ~SkyRegistrationMessage() override;
  explicit PROTOBUF_CONSTEXPR SkyRegistrationMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SkyRegistrationMessage(const SkyRegistrationMessage& from);
  SkyRegistrationMessage(SkyRegistrationMessage&& from) noexcept
    : SkyRegistrationMessage() {
    *this = ::std::move(from);
  }

  inline SkyRegistrationMessage& operator=(const SkyRegistrationMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline SkyRegistrationMessage& operator=(SkyRegistrationMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SkyRegistrationMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const SkyRegistrationMessage* internal_default_instance() {
    return reinterpret_cast<const SkyRegistrationMessage*>(
               &_SkyRegistrationMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SkyRegistrationMessage& a, SkyRegistrationMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(SkyRegistrationMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SkyRegistrationMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SkyRegistrationMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SkyRegistrationMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SkyRegistrationMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SkyRegistrationMessage& from) {
    SkyRegistrationMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SkyRegistrationMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage";
  }
  protected:
  explicit SkyRegistrationMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kNodeIdFieldNumber = 2,
    kRegistrationFieldNumber = 3,
  };
  // string timestamp = 1;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string nodeId = 2;
  void clear_nodeid();
  const std::string& nodeid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nodeid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nodeid();
  PROTOBUF_NODISCARD std::string* release_nodeid();
  void set_allocated_nodeid(std::string* nodeid);
  private:
  const std::string& _internal_nodeid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nodeid(const std::string& value);
  std::string* _internal_mutable_nodeid();
  public:

  // .sapient_msg.bsi_flex_335_v2_0.Registration registration = 3;
  bool has_registration() const;
  private:
  bool _internal_has_registration() const;
  public:
  void clear_registration();
  const ::sapient_msg::bsi_flex_335_v2_0::Registration& registration() const;
  PROTOBUF_NODISCARD ::sapient_msg::bsi_flex_335_v2_0::Registration* release_registration();
  ::sapient_msg::bsi_flex_335_v2_0::Registration* mutable_registration();
  void set_allocated_registration(::sapient_msg::bsi_flex_335_v2_0::Registration* registration);
  private:
  const ::sapient_msg::bsi_flex_335_v2_0::Registration& _internal_registration() const;
  ::sapient_msg::bsi_flex_335_v2_0::Registration* _internal_mutable_registration();
  public:
  void unsafe_arena_set_allocated_registration(
      ::sapient_msg::bsi_flex_335_v2_0::Registration* registration);
  ::sapient_msg::bsi_flex_335_v2_0::Registration* unsafe_arena_release_registration();

  // @@protoc_insertion_point(class_scope:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nodeid_;
    ::sapient_msg::bsi_flex_335_v2_0::Registration* registration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sky_5fregistration_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SkyRegistrationMessage

// string timestamp = 1;
inline void SkyRegistrationMessage::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& SkyRegistrationMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SkyRegistrationMessage::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp)
}
inline std::string* SkyRegistrationMessage::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp)
  return _s;
}
inline const std::string& SkyRegistrationMessage::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void SkyRegistrationMessage::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* SkyRegistrationMessage::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* SkyRegistrationMessage::release_timestamp() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp)
  return _impl_.timestamp_.Release();
}
inline void SkyRegistrationMessage::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.timestamp)
}

// string nodeId = 2;
inline void SkyRegistrationMessage::clear_nodeid() {
  _impl_.nodeid_.ClearToEmpty();
}
inline const std::string& SkyRegistrationMessage::nodeid() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId)
  return _internal_nodeid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SkyRegistrationMessage::set_nodeid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nodeid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId)
}
inline std::string* SkyRegistrationMessage::mutable_nodeid() {
  std::string* _s = _internal_mutable_nodeid();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId)
  return _s;
}
inline const std::string& SkyRegistrationMessage::_internal_nodeid() const {
  return _impl_.nodeid_.Get();
}
inline void SkyRegistrationMessage::_internal_set_nodeid(const std::string& value) {
  
  _impl_.nodeid_.Set(value, GetArenaForAllocation());
}
inline std::string* SkyRegistrationMessage::_internal_mutable_nodeid() {
  
  return _impl_.nodeid_.Mutable(GetArenaForAllocation());
}
inline std::string* SkyRegistrationMessage::release_nodeid() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId)
  return _impl_.nodeid_.Release();
}
inline void SkyRegistrationMessage::set_allocated_nodeid(std::string* nodeid) {
  if (nodeid != nullptr) {
    
  } else {
    
  }
  _impl_.nodeid_.SetAllocated(nodeid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nodeid_.IsDefault()) {
    _impl_.nodeid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.nodeId)
}

// .sapient_msg.bsi_flex_335_v2_0.Registration registration = 3;
inline bool SkyRegistrationMessage::_internal_has_registration() const {
  return this != internal_default_instance() && _impl_.registration_ != nullptr;
}
inline bool SkyRegistrationMessage::has_registration() const {
  return _internal_has_registration();
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Registration& SkyRegistrationMessage::_internal_registration() const {
  const ::sapient_msg::bsi_flex_335_v2_0::Registration* p = _impl_.registration_;
  return p != nullptr ? *p : reinterpret_cast<const ::sapient_msg::bsi_flex_335_v2_0::Registration&>(
      ::sapient_msg::bsi_flex_335_v2_0::_Registration_default_instance_);
}
inline const ::sapient_msg::bsi_flex_335_v2_0::Registration& SkyRegistrationMessage::registration() const {
  // @@protoc_insertion_point(field_get:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.registration)
  return _internal_registration();
}
inline void SkyRegistrationMessage::unsafe_arena_set_allocated_registration(
    ::sapient_msg::bsi_flex_335_v2_0::Registration* registration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.registration_);
  }
  _impl_.registration_ = registration;
  if (registration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.registration)
}
inline ::sapient_msg::bsi_flex_335_v2_0::Registration* SkyRegistrationMessage::release_registration() {
  
  ::sapient_msg::bsi_flex_335_v2_0::Registration* temp = _impl_.registration_;
  _impl_.registration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Registration* SkyRegistrationMessage::unsafe_arena_release_registration() {
  // @@protoc_insertion_point(field_release:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.registration)
  
  ::sapient_msg::bsi_flex_335_v2_0::Registration* temp = _impl_.registration_;
  _impl_.registration_ = nullptr;
  return temp;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Registration* SkyRegistrationMessage::_internal_mutable_registration() {
  
  if (_impl_.registration_ == nullptr) {
    auto* p = CreateMaybeMessage<::sapient_msg::bsi_flex_335_v2_0::Registration>(GetArenaForAllocation());
    _impl_.registration_ = p;
  }
  return _impl_.registration_;
}
inline ::sapient_msg::bsi_flex_335_v2_0::Registration* SkyRegistrationMessage::mutable_registration() {
  ::sapient_msg::bsi_flex_335_v2_0::Registration* _msg = _internal_mutable_registration();
  // @@protoc_insertion_point(field_mutable:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.registration)
  return _msg;
}
inline void SkyRegistrationMessage::set_allocated_registration(::sapient_msg::bsi_flex_335_v2_0::Registration* registration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.registration_);
  }
  if (registration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(registration));
    if (message_arena != submessage_arena) {
      registration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, registration, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.registration_ = registration;
  // @@protoc_insertion_point(field_set_allocated:sapient_msg.bsi_flex_335_v2_0.SkyRegistrationMessage.registration)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sky_5fregistration_2eproto
