// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: velocity.proto

#include "velocity.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
PROTOBUF_CONSTEXPR ENUVelocity::ENUVelocity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.east_rate_)*/0
  , /*decltype(_impl_.north_rate_)*/0
  , /*decltype(_impl_.up_rate_)*/0
  , /*decltype(_impl_.east_rate_error_)*/0
  , /*decltype(_impl_.north_rate_error_)*/0
  , /*decltype(_impl_.up_rate_error_)*/0} {}
struct ENUVelocityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ENUVelocityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ENUVelocityDefaultTypeInternal() {}
  union {
    ENUVelocity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ENUVelocityDefaultTypeInternal _ENUVelocity_default_instance_;
PROTOBUF_CONSTEXPR ENUVelocityUnits::ENUVelocityUnits(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.east_north_rate_units_)*/0
  , /*decltype(_impl_.up_rate_units_)*/0} {}
struct ENUVelocityUnitsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ENUVelocityUnitsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ENUVelocityUnitsDefaultTypeInternal() {}
  union {
    ENUVelocityUnits _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ENUVelocityUnitsDefaultTypeInternal _ENUVelocityUnits_default_instance_;
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
static ::_pb::Metadata file_level_metadata_velocity_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_velocity_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_velocity_2eproto = nullptr;

const uint32_t TableStruct_velocity_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.east_rate_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.north_rate_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.up_rate_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.east_rate_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.north_rate_error_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity, _impl_.up_rate_error_),
  0,
  1,
  2,
  3,
  4,
  5,
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits, _impl_.east_north_rate_units_),
  PROTOBUF_FIELD_OFFSET(::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits, _impl_.up_rate_units_),
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::ENUVelocity)},
  { 18, 26, -1, sizeof(::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sapient_msg::bsi_flex_335_v2_0::_ENUVelocity_default_instance_._instance,
  &::sapient_msg::bsi_flex_335_v2_0::_ENUVelocityUnits_default_instance_._instance,
};

const char descriptor_table_protodef_velocity_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016velocity.proto\022\035sapient_msg.bsi_flex_3"
  "35_v2_0\032\023proto_options.proto\"\241\002\n\013ENUVelo"
  "city\022\036\n\teast_rate\030\001 \001(\001B\006\212\265\030\002\010\001H\000\210\001\001\022\037\n\n"
  "north_rate\030\002 \001(\001B\006\212\265\030\002\010\001H\001\210\001\001\022\024\n\007up_rate"
  "\030\003 \001(\001H\002\210\001\001\022\034\n\017east_rate_error\030\004 \001(\001H\003\210\001"
  "\001\022\035\n\020north_rate_error\030\005 \001(\001H\004\210\001\001\022\032\n\rup_r"
  "ate_error\030\006 \001(\001H\005\210\001\001B\014\n\n_east_rateB\r\n\013_n"
  "orth_rateB\n\n\010_up_rateB\022\n\020_east_rate_erro"
  "rB\023\n\021_north_rate_errorB\020\n\016_up_rate_error"
  "\"\334\001\n\020ENUVelocityUnits\022U\n\025east_north_rate"
  "_units\030\001 \001(\0162).sapient_msg.bsi_flex_335_"
  "v2_0.SpeedUnitsB\006\212\265\030\002\010\001H\000\210\001\001\022E\n\rup_rate_"
  "units\030\002 \001(\0162).sapient_msg.bsi_flex_335_v"
  "2_0.SpeedUnitsH\001\210\001\001B\030\n\026_east_north_rate_"
  "unitsB\020\n\016_up_rate_units*^\n\nSpeedUnits\022\033\n"
  "\027SPEED_UNITS_UNSPECIFIED\020\000\022\022\n\016SPEED_UNIT"
  "S_MS\020\001\022\023\n\017SPEED_UNITS_KPH\020\002\"\004\010\003\020\003\"\004\010\004\020\004B"
  "6\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\r"
  "VelocityProtoP\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_velocity_2eproto_deps[1] = {
  &::descriptor_table_proto_5foptions_2eproto,
};
static ::_pbi::once_flag descriptor_table_velocity_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_velocity_2eproto = {
    false, false, 743, descriptor_table_protodef_velocity_2eproto,
    "velocity.proto",
    &descriptor_table_velocity_2eproto_once, descriptor_table_velocity_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_velocity_2eproto::offsets,
    file_level_metadata_velocity_2eproto, file_level_enum_descriptors_velocity_2eproto,
    file_level_service_descriptors_velocity_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_velocity_2eproto_getter() {
  return &descriptor_table_velocity_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_velocity_2eproto(&descriptor_table_velocity_2eproto);
namespace sapient_msg {
namespace bsi_flex_335_v2_0 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SpeedUnits_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_velocity_2eproto);
  return file_level_enum_descriptors_velocity_2eproto[0];
}
bool SpeedUnits_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ENUVelocity::_Internal {
 public:
  using HasBits = decltype(std::declval<ENUVelocity>()._impl_._has_bits_);
  static void set_has_east_rate(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_north_rate(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_up_rate(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_east_rate_error(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_north_rate_error(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_up_rate_error(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

ENUVelocity::ENUVelocity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
}
ENUVelocity::ENUVelocity(const ENUVelocity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ENUVelocity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.east_rate_){}
    , decltype(_impl_.north_rate_){}
    , decltype(_impl_.up_rate_){}
    , decltype(_impl_.east_rate_error_){}
    , decltype(_impl_.north_rate_error_){}
    , decltype(_impl_.up_rate_error_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.east_rate_, &from._impl_.east_rate_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.up_rate_error_) -
    reinterpret_cast<char*>(&_impl_.east_rate_)) + sizeof(_impl_.up_rate_error_));
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
}

inline void ENUVelocity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.east_rate_){0}
    , decltype(_impl_.north_rate_){0}
    , decltype(_impl_.up_rate_){0}
    , decltype(_impl_.east_rate_error_){0}
    , decltype(_impl_.north_rate_error_){0}
    , decltype(_impl_.up_rate_error_){0}
  };
}

ENUVelocity::~ENUVelocity() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ENUVelocity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ENUVelocity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ENUVelocity::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.east_rate_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.up_rate_error_) -
        reinterpret_cast<char*>(&_impl_.east_rate_)) + sizeof(_impl_.up_rate_error_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ENUVelocity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double east_rate = 1 [(.sapient_msg.field_options) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_east_rate(&has_bits);
          _impl_.east_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double north_rate = 2 [(.sapient_msg.field_options) = {
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_north_rate(&has_bits);
          _impl_.north_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double up_rate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_up_rate(&has_bits);
          _impl_.up_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double east_rate_error = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_east_rate_error(&has_bits);
          _impl_.east_rate_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double north_rate_error = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _Internal::set_has_north_rate_error(&has_bits);
          _impl_.north_rate_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double up_rate_error = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_up_rate_error(&has_bits);
          _impl_.up_rate_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ENUVelocity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional double east_rate = 1 [(.sapient_msg.field_options) = {
  if (_internal_has_east_rate()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_east_rate(), target);
  }

  // optional double north_rate = 2 [(.sapient_msg.field_options) = {
  if (_internal_has_north_rate()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_north_rate(), target);
  }

  // optional double up_rate = 3;
  if (_internal_has_up_rate()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_up_rate(), target);
  }

  // optional double east_rate_error = 4;
  if (_internal_has_east_rate_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_east_rate_error(), target);
  }

  // optional double north_rate_error = 5;
  if (_internal_has_north_rate_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_north_rate_error(), target);
  }

  // optional double up_rate_error = 6;
  if (_internal_has_up_rate_error()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_up_rate_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  return target;
}

size_t ENUVelocity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional double east_rate = 1 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional double north_rate = 2 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional double up_rate = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double east_rate_error = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double north_rate_error = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double up_rate_error = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ENUVelocity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ENUVelocity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ENUVelocity::GetClassData() const { return &_class_data_; }


void ENUVelocity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ENUVelocity*>(&to_msg);
  auto& from = static_cast<const ENUVelocity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.east_rate_ = from._impl_.east_rate_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.north_rate_ = from._impl_.north_rate_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.up_rate_ = from._impl_.up_rate_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.east_rate_error_ = from._impl_.east_rate_error_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.north_rate_error_ = from._impl_.north_rate_error_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.up_rate_error_ = from._impl_.up_rate_error_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ENUVelocity::CopyFrom(const ENUVelocity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ENUVelocity::IsInitialized() const {
  return true;
}

void ENUVelocity::InternalSwap(ENUVelocity* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ENUVelocity, _impl_.up_rate_error_)
      + sizeof(ENUVelocity::_impl_.up_rate_error_)
      - PROTOBUF_FIELD_OFFSET(ENUVelocity, _impl_.east_rate_)>(
          reinterpret_cast<char*>(&_impl_.east_rate_),
          reinterpret_cast<char*>(&other->_impl_.east_rate_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ENUVelocity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_velocity_2eproto_getter, &descriptor_table_velocity_2eproto_once,
      file_level_metadata_velocity_2eproto[0]);
}

// ===================================================================

class ENUVelocityUnits::_Internal {
 public:
  using HasBits = decltype(std::declval<ENUVelocityUnits>()._impl_._has_bits_);
  static void set_has_east_north_rate_units(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_up_rate_units(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

ENUVelocityUnits::ENUVelocityUnits(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
}
ENUVelocityUnits::ENUVelocityUnits(const ENUVelocityUnits& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ENUVelocityUnits* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.east_north_rate_units_){}
    , decltype(_impl_.up_rate_units_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.east_north_rate_units_, &from._impl_.east_north_rate_units_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.up_rate_units_) -
    reinterpret_cast<char*>(&_impl_.east_north_rate_units_)) + sizeof(_impl_.up_rate_units_));
  // @@protoc_insertion_point(copy_constructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
}

inline void ENUVelocityUnits::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.east_north_rate_units_){0}
    , decltype(_impl_.up_rate_units_){0}
  };
}

ENUVelocityUnits::~ENUVelocityUnits() {
  // @@protoc_insertion_point(destructor:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ENUVelocityUnits::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ENUVelocityUnits::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ENUVelocityUnits::Clear() {
// @@protoc_insertion_point(message_clear_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.east_north_rate_units_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.up_rate_units_) -
        reinterpret_cast<char*>(&_impl_.east_north_rate_units_)) + sizeof(_impl_.up_rate_units_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ENUVelocityUnits::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits east_north_rate_units = 1 [(.sapient_msg.field_options) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_east_north_rate_units(static_cast<::sapient_msg::bsi_flex_335_v2_0::SpeedUnits>(val));
        } else
          goto handle_unusual;
        continue;
      // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits up_rate_units = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_up_rate_units(static_cast<::sapient_msg::bsi_flex_335_v2_0::SpeedUnits>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ENUVelocityUnits::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits east_north_rate_units = 1 [(.sapient_msg.field_options) = {
  if (_internal_has_east_north_rate_units()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_east_north_rate_units(), target);
  }

  // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits up_rate_units = 2;
  if (_internal_has_up_rate_units()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_up_rate_units(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  return target;
}

size_t ENUVelocityUnits::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits east_north_rate_units = 1 [(.sapient_msg.field_options) = {
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_east_north_rate_units());
    }

    // optional .sapient_msg.bsi_flex_335_v2_0.SpeedUnits up_rate_units = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_up_rate_units());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ENUVelocityUnits::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ENUVelocityUnits::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ENUVelocityUnits::GetClassData() const { return &_class_data_; }


void ENUVelocityUnits::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ENUVelocityUnits*>(&to_msg);
  auto& from = static_cast<const ENUVelocityUnits&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.east_north_rate_units_ = from._impl_.east_north_rate_units_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.up_rate_units_ = from._impl_.up_rate_units_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ENUVelocityUnits::CopyFrom(const ENUVelocityUnits& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ENUVelocityUnits::IsInitialized() const {
  return true;
}

void ENUVelocityUnits::InternalSwap(ENUVelocityUnits* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ENUVelocityUnits, _impl_.up_rate_units_)
      + sizeof(ENUVelocityUnits::_impl_.up_rate_units_)
      - PROTOBUF_FIELD_OFFSET(ENUVelocityUnits, _impl_.east_north_rate_units_)>(
          reinterpret_cast<char*>(&_impl_.east_north_rate_units_),
          reinterpret_cast<char*>(&other->_impl_.east_north_rate_units_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ENUVelocityUnits::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_velocity_2eproto_getter, &descriptor_table_velocity_2eproto_once,
      file_level_metadata_velocity_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bsi_flex_335_v2_0
}  // namespace sapient_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::ENUVelocity*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::ENUVelocity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::ENUVelocity >(arena);
}
template<> PROTOBUF_NOINLINE ::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits*
Arena::CreateMaybeMessage< ::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sapient_msg::bsi_flex_335_v2_0::ENUVelocityUnits >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
